
# set NF modules in kernel

define SIP_ENABLE
@$(call MESSAGE,Enabling kernel NF SIP modules [NF_NAT_SIP | NF_CONNTRACK_SIP])
@$(call KCONFIG_SET_OPT,CONFIG_NF_CONNTRACK_SIP,m,$(LINUX_CONFIG))
@
endef

define SIP_DISABLE
@$(call MESSAGE,Disabling kernel NF SIP modules [NF_NAT_SIP | NF_CONNTRACK_SIP])
@$(call KCONFIG_DISABLE_OPT,CONFIG_NF_CONNTRACK_SIP,$(LINUX_CONFIG))
@
endef

define RTSP_ENABLE
@$(call MESSAGE,Enabling kernel NF RTSP modules [NF_CONNTRACK_RTSP])
@$(call KCONFIG_SET_OPT,CONFIG_NF_CONNTRACK_RTSP,m,$(LINUX_CONFIG))
@
endef

define RTSP_DISABLE
@$(call MESSAGE,Disabling kernel NF RTSP modules [NF_CONNTRACK_RTSP])
@$(call KCONFIG_DISABLE_OPT,CONFIG_NF_CONNTRACK_RTSP,$(LINUX_CONFIG))
@
endef

define NAT_H323_ENABLE
@$(call MESSAGE,Enabling kernel NF NAT_H323 modules [NF_NAT_H323 | NF_CONNTRACK_H323])
@$(call KCONFIG_SET_OPT,CONFIG_NF_CONNTRACK_H323,m,$(LINUX_CONFIG))
@
endef

define NAT_H323_DISABLE
@$(call MESSAGE,Disabling kernel NF NAT_H323 modules [NF_NAT_H323 | NF_CONNTRACK_H323])
@$(call KCONFIG_DISABLE_OPT,CONFIG_NF_CONNTRACK_H323,$(LINUX_CONFIG))
@
endef

define URL_FILTER_ENABLE
@$(call MESSAGE,Enabling kernel URL Filter modules [NETFILTER_NETLINK_QUEUE | NETFILTER_NETLINK_QUEUE_CT | NETFILTER_XT_TARGET_NFQUEUE])
@$(call KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_NETLINK_QUEUE,$(LINUX_CONFIG))
@$(call KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_NETLINK_QUEUE_CT,$(LINUX_CONFIG))
@$(call KCONFIG_ENABLE_OPT,CONFIG_NETFILTER_XT_TARGET_NFQUEUE,$(LINUX_CONFIG))
@$(call KCONFIG_DISABLE_OPT_IF_NOT_ENABLED,CONFIG_NF_CT_NETLINK_HELPER,$(LINUX_CONFIG))
@$(call KCONFIG_DISABLE_OPT_IF_NOT_ENABLED,CONFIG_NETFILTER_NETLINK_GLUE_CT,$(LINUX_CONFIG))
@
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_SIP),SIP_ENABLE,SIP_DISABLE)
LINUX_ADDONS += $(if $(BR2_SUPPORT_RTSP),RTSP_ENABLE,RTSP_DISABLE)
LINUX_ADDONS += $(if $(BR2_SUPPORT_NAT_H323),NAT_H323_ENABLE,NAT_H323_DISABLE)
LINUX_ADDONS += $(if $(BR2_PACKAGE_URLFILTERD),URL_FILTER_ENABLE)
