ifeq ($(RALINK_MTK_WIFI_DRV_RLT_WIFI),y)
ifeq ($(RALINK_MTK_WIFI_5GHZ_MT7612EN),y)
define DUAL_MT7612E_ENABLE
$(call MESSAGE,"Enabling Dual MT7612E wi-fi configuration") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_DRU_WIFI_DUAL_MT7612E_FIX_ENUM, $(LINUX_CONFIG)) ;
endef

define DUAL_MT7612E_DISABLE
$(call MESSAGE,"Disabling Dual MT7612E wi-fi configuration") ;
$(call KCONFIG_DISABLE_OPT,CONFIG_DRU_WIFI_DUAL_MT7612E_FIX_ENUM, $(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_WIFI_DUAL_MT7612E),DUAL_MT7612E_ENABLE,DUAL_MT7612E_DISABLE)

endif
endif


ifeq ($(BR2_rlx_wifi),y)
#WPA3
define SUPPORT_WIFI_WPA3_ENABLE
$(call MESSAGE,"Enable support wpa3-sae") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_WPA3_SUPPORT, $(LINUX_CONFIG)) ;
endef

define SUPPORT_WIFI_WPA3_DISABLE
$(call MESSAGE,"Disable support wpa3-sae") ;
$(call KCONFIG_DISABLE_OPT,CONFIG_RTL_WPA3_SUPPORT, $(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_WIFI_WPA3),SUPPORT_WIFI_WPA3_ENABLE,SUPPORT_WIFI_WPA3_DISABLE)

#MIBSYNC
define ENABLE_COMAPI_CFGFILE
$(call MESSAGE,"Enabling COMAPI_CFGFILE") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_COMAPI_CFGFILE, $(LINUX_CONFIG)) ;
endef

define DISABLE_COMAPI_CFGFILE
$(call MESSAGE,"Disabling COMAPI_CFGFILE") ;
$(call KCONFIG_DISABLE_OPT,CONFIG_RTL_COMAPI_CFGFILE, $(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_WIFI_MIBSYNC),DISABLE_COMAPI_CFGFILE,ENABLE_COMAPI_CFGFILE)

#11K
define ENABLE_11K
$(call MESSAGE,"Enabling 11K support") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_DOT11K_SUPPORT,$(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_WIFI_11K),ENABLE_11K)

#11W
define ENABLE_11W
$(call MESSAGE,"Enabling 11W support") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_11W_SUPPORT,$(LINUX_CONFIG)) ;
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_11W_CLI_SUPPORT,$(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_WIFI_PMF),ENABLE_11W)

define TXPWR_LIMIT_ENABLE
$(call MESSAGE,"Enabling TX Power Limit feature") ;
$(call KCONFIG_ENABLE_OPT,CONFIG_TXPWR_LMT, $(LINUX_CONFIG)) ;
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_WIFI_TXPWR_LIMIT),TXPWR_LIMIT_ENABLE)

define ENABLE_DFS
$(call MESSAGE,"Enable DFS");
$(call KCONFIG_ENABLE_OPT,CONFIG_RTL_DFS_SUPPORT,$(LINUX_CONFIG));
endef

define DISABLE_DFS
$(call MESSAGE,"Disable DFS");
$(call KCONFIG_DISABLE_OPT,CONFIG_RTL_DFS_SUPPORT,$(LINUX_CONFIG));
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_DFS),ENABLE_DFS,DISABLE_DFS)
endif # BR2_rlx_wifi
