
# set L2TPV3 modules in kernel

define L2TPV3_ENABLE
@$(call MESSAGE,Enabling kernel L2TPv3 modules [L2TP_V3 | L2TP_IP | L2TP_ETH])
@$(call KCONFIG_ENABLE_OPT,CONFIG_L2TP_V3,$(LINUX_CONFIG))
@$(call KCONFIG_SET_OPT,CONFIG_L2TP_IP,m,$(LINUX_CONFIG))
@$(call KCONFIG_SET_OPT,CONFIG_L2TP_ETH,m,$(LINUX_CONFIG))
@
endef

define L2TPV3_DISABLE
@$(call MESSAGE,Disabling kernel L2TPv3 module [L2TP_V3 | L2TP_IP | L2TP_ETH])
@$(call KCONFIG_DISABLE_OPT,CONFIG_L2TP_ETH,$(LINUX_CONFIG))
@$(call KCONFIG_DISABLE_OPT,CONFIG_L2TP_IP,$(LINUX_CONFIG))
@$(call KCONFIG_DISABLE_OPT,CONFIG_L2TP_V3,$(LINUX_CONFIG))
@
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_STATIC_L2TPv3),L2TPV3_ENABLE,L2TPV3_DISABLE)
