################################################################################
#
# strongswan
#
################################################################################

STRONGSWAN_VERSION = $(patsubst "%",%,$(BR2_PACKAGE_STRONGSWAN_VERSION))
STRONGSWAN_SITE = $(DLINK_GIT_STORAGE)/strongswan
STRONGSWAN_LICENSE = GPL-2.0-or-later
STRONGSWAN_LICENSE_FILES = COPYING LICENSE
STRONGSWAN_DEPENDENCIES = host-pkg-config
STRONGSWAN_INSTALL_STAGING = YES

# Для версии 5.5.1 использовался DLINK_GIT_STORAGE
# Все последущие версии лучше собирать через DLINK_STORAGE
ifeq ($(BR2_PACKAGE_STRONGSWAN_USE_STORAGE),y)
STRONGSWAN_SITE = $(DLINK_STORAGE)
STRONGSWAN_SOURCE = strongswan-$(STRONGSWAN_VERSION).tar.gz
endif

# С версии 5.8.2 сборка фейлится, если нет gperf.
ifeq ($(BR2_PACKAGE_STRONGSWAN_WITH_HOST_GPERF),y)
STRONGSWAN_DEPENDENCIES += host-gperf
endif

STRONGSWAN_DEPENDENCIES += deuteron_framework

STRONGSWAN_CONF_OPT += LDFLAGS="-L$(STAGING_DIR)/lib -L$(STAGING_DIR)/usr/lib"
STRONGSWAN_CONF_OPT += LIBS="-ld_service_notify -ljansson -Wl,-rpath-link,$(STAGING_DIR)/lib -Wl,-rpath-link,$(STAGING_DIR)/usr/lib"

STRING_OPT_MINIMAL = \
	--disable-defaults \
	--enable-attr=yes \
	--enable-charon=yes \
	--enable-kernel-netlink=yes \
	--enable-nonce=yes \
	--enable-resolve=yes \
	--enable-socket-default=yes \
	--enable-stroke=yes \
	--enable-xauth-generic=yes \
	--enable-openssl=yes \
	--enable-random=yes \
	--enable-ikev1=yes \
	--disable-ikev2 \
	--enable-monolithic=yes

STRING_OPT_DEFAULT = $(STRING_OPT_MINIMAL) \
	--enable-ikev2

STRING_OPT_FULL = \
	--enable-all

# 1)enable-test-vectors - проверка crypto-алгоритмов (самотестирование).
#   Нужно увеличивать время запуска charon-демона, т.к. на данный момент там хардкод на 10 секунд: src/starter/invokecharon.c
# 2)load-tester - тестирование максимальной нагрузки ipsec-туннелей. Позволяет одновременно настраивать тысячи туннелей против самого демона или удаленного хоста.
#   Использование этого плагина открывает уязвимости при аутентификации.
# 3)integrity-test - проверка целостности исполняемых файлов, библиотек, плагинов, конфигураций.
# 4)conftest - большой набор действий с изменением пакетов при IKE обмене.
# 5)save-keys - сохраняет IKE/ESP-ключи совместимые с Wireshark в определенные файлы.
# TODO: check others tests
STRING_OPT_TEST = \
	--enable-test-vectors \
	--enable-load-tester \
	--enable-conftest \
	--enable-save-keys \
	--enable-imc-test \
	--enable-imv-test \
	--enable-android-log \
	--enable-leak-detective \
	--enable-lock-profiler \
	--enable-log-thread-ids \

	# --enable-bfd-backtraces \
	# --enable-dbghelp-backtraces \
	# --enable-integrity-test \

ifneq ($(BR2_PACKAGE_STRONGSWAN_BUILD_ADVANCED),y)

# minimal
ifeq ($(BR2_PACKAGE_STRONGSWAN_BUILD_MINIMAL),y)
STRONGSWAN_CONF_OPT += $(STRING_OPT_MINIMAL)
endif #BR2_PACKAGE_STRONGSWAN_BUILD_MINIMAL

# default
ifeq ($(BR2_PACKAGE_STRONGSWAN_BUILD_DEFAULT),y)
STRONGSWAN_CONF_OPT += $(STRING_OPT_DEFAULT)
endif #BR2_PACKAGE_STRONGSWAN_BUILD_DEFAULT

# full
ifeq ($(BR2_PACKAGE_STRONGSWAN_BUILD_FULL),y)
STRONGSWAN_CONF_OPT += $(STRING_OPT_FULL)
endif #BR2_PACKAGE_STRONGSWAN_BUILD_FULL

# advanced
else #BR2_PACKAGE_STRONGSWAN_BUILD_ADVANCED

# Disable all default plugins and enable only the necessary
STRONGSWAN_CONF_OPT += --disable-defaults

#Utilits/Scripts
ifeq ($(BR2_PACKAGE_STRONGSWAN_CHARON),y)
STRONGSWAN_CONF_OPT += --enable-charon=yes
endif #BR2_PACKAGE_STRONGSWAN_CHARON
ifeq ($(BR2_PACKAGE_STRONGSWAN_IKEV1),y)
STRONGSWAN_CONF_OPT += --enable-ikev1=yes
endif #BR2_PACKAGE_STRONGSWAN_IKEV1
ifeq ($(BR2_PACKAGE_STRONGSWAN_IKEV2),y)
STRONGSWAN_CONF_OPT += --enable-ikev2=yes
endif #BR2_PACKAGE_STRONGSWAN_IKEV2
ifeq ($(BR2_PACKAGE_STRONGSWAN_CMD),y)
STRONGSWAN_CONF_OPT += --enable-cmd=yes
endif #BR2_PACKAGE_STRONGSWAN_CMD
ifeq ($(BR2_PACKAGE_STRONGSWAN_NM),y)
STRONGSWAN_CONF_OPT += --enable-nm=yes
endif #BR2_PACKAGE_STRONGSWAN_NM
ifeq ($(BR2_PACKAGE_STRONGSWAN_SYSTEMD),y)
STRONGSWAN_CONF_OPT += --enable-systemd=yes
endif #BR2_PACKAGE_STRONGSWAN_SYSTEMD
ifeq ($(BR2_PACKAGE_STRONGSWAN_INTEGRITY_TEST),y)
STRONGSWAN_CONF_OPT += --enable-integrity-test=yes
endif #BR2_PACKAGE_STRONGSWAN_INTEGRITY_TEST
ifeq ($(BR2_PACKAGE_STRONGSWAN_CONFTEST),y)
STRONGSWAN_CONF_OPT += --enable-conftest=yes
endif #BR2_PACKAGE_STRONGSWAN_CONFTEST
ifeq ($(BR2_PACKAGE_STRONGSWAN_MANAGER),y)
STRONGSWAN_CONF_OPT += --enable-manager=yes
endif #BR2_PACKAGE_STRONGSWAN_MANAGER
ifeq ($(BR2_PACKAGE_STRONGSWAN_SCEPCLIENT),y)
STRONGSWAN_CONF_OPT += --enable-scepclient=yes
endif #BR2_PACKAGE_STRONGSWAN_SCEPCLIENT
ifeq ($(BR2_PACKAGE_STRONGSWAN_STROKE),y)
STRONGSWAN_CONF_OPT += --enable-stroke=yes
endif #BR2_PACKAGE_STRONGSWAN_STROKE
ifeq ($(BR2_PACKAGE_STRONGSWAN_SWANCTL),y)
STRONGSWAN_CONF_OPT += --enable-swanctl=yes
endif #BR2_PACKAGE_STRONGSWAN_SWANCTL
ifeq ($(BR2_PACKAGE_STRONGSWAN_EXT_AUTH),y)
STRONGSWAN_CONF_OPT += --enable-ext-auth=yes
endif #BR2_PACKAGE_STRONGSWAN_EXT_AUTH
ifeq ($(BR2_PACKAGE_STRONGSWAN_UPDOWN),y)
STRONGSWAN_CONF_OPT += --enable-updown=yes
endif #BR2_PACKAGE_STRONGSWAN_UPDOWN
ifeq ($(BR2_PACKAGE_STRONGSWAN_FUZZING),y)
STRONGSWAN_CONF_OPT += --enable-fuzzing=yes
endif #BR2_PACKAGE_STRONGSWAN_FUZZING
ifeq ($(BR2_PACKAGE_STRONGSWAN_SCRIPTS),y)
STRONGSWAN_CONF_OPT += --enable-scripts=yes
endif #BR2_PACKAGE_STRONGSWAN_SCRIPTS

# Directories
ifneq ($(BR2_PACKAGE_STRONGSWAN_BINDIR),"")
STRONGSWAN_CONF_OPT += --bindir=$(BR2_PACKAGE_STRONGSWAN_BINDIR)
endif # BR2_PACKAGE_STRONGSWAN_BINDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_SBINDIR),"")
STRONGSWAN_CONF_OPT += --sbindir=$(BR2_PACKAGE_STRONGSWAN_SBINDIR)
endif # BR2_PACKAGE_STRONGSWAN_SBINDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_LIBEXECDIR),"")
STRONGSWAN_CONF_OPT += --libexecdir=$(BR2_PACKAGE_STRONGSWAN_LIBEXECDIR)
endif # BR2_PACKAGE_STRONGSWAN_LIBEXECDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_SYSCONFDIR),"")
STRONGSWAN_CONF_OPT += --sysconfdir=$(BR2_PACKAGE_STRONGSWAN_SYSCONFDIR)
endif # BR2_PACKAGE_STRONGSWAN_SYSCONFDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_LIBDIR),"")
STRONGSWAN_CONF_OPT += --libdir=$(BR2_PACKAGE_STRONGSWAN_LIBDIR)
endif # BR2_PACKAGE_STRONGSWAN_LIBDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_SHAREDSTATEDIR),"")
STRONGSWAN_CONF_OPT += --sharedstatedir=$(BR2_PACKAGE_STRONGSWAN_SHAREDSTATEDIR)
endif # BR2_PACKAGE_STRONGSWAN_SHAREDSTATEDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_LOCALSTATEDIR),"")
STRONGSWAN_CONF_OPT += --localstatedir=$(BR2_PACKAGE_STRONGSWAN_LOCALSTATEDIR)
endif # BR2_PACKAGE_STRONGSWAN_LOCALSTATEDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_RUNSTATEDIR),"")
STRONGSWAN_CONF_OPT += --runstatedir=$(BR2_PACKAGE_STRONGSWAN_RUNSTATEDIR)
endif # BR2_PACKAGE_STRONGSWAN_RUNSTATEDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_INCLUDEDIR),"")
STRONGSWAN_CONF_OPT += --includedir=$(BR2_PACKAGE_STRONGSWAN_INCLUDEDIR)
endif # BR2_PACKAGE_STRONGSWAN_INCLUDEDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_OLDINCLUDEDIR),"")
STRONGSWAN_CONF_OPT += --oldincludedir=$(BR2_PACKAGE_STRONGSWAN_OLDINCLUDEDIR)
endif # BR2_PACKAGE_STRONGSWAN_OLDINCLUDEDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_DATAROOTDIR),"")
STRONGSWAN_CONF_OPT += --datarootdir=$(BR2_PACKAGE_STRONGSWAN_DATAROOTDIR)
endif # BR2_PACKAGE_STRONGSWAN_DATAROOTDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_DATADIR),"")
STRONGSWAN_CONF_OPT += --datadir=$(BR2_PACKAGE_STRONGSWAN_DATADIR)
endif # BR2_PACKAGE_STRONGSWAN_DATADIR

# Names
ifneq ($(BR2_PACKAGE_STRONGSWAN_PROGRAM_PREFIX),"")
STRONGSWAN_CONF_OPT += --program-prefix=$(BR2_PACKAGE_STRONGSWAN_PROGRAM_PREFIX)
endif # BR2_PACKAGE_STRONGSWAN_PROGRAM_PREFIX
ifneq ($(BR2_PACKAGE_STRONGSWAN_PROGRAM_SUFFIX),"")
STRONGSWAN_CONF_OPT += --program-suffix=$(BR2_PACKAGE_STRONGSWAN_PROGRAM_SUFFIX)
endif # BR2_PACKAGE_STRONGSWAN_PROGRAM_SUFFIX
ifneq ($(BR2_PACKAGE_STRONGSWAN_PROGRAM_TRANSFORM_NAME),"")
STRONGSWAN_CONF_OPT += --program-transform-name=$(BR2_PACKAGE_STRONGSWAN_PROGRAM_TRANSFORM_NAME)
endif # BR2_PACKAGE_STRONGSWAN_PROGRAM_TRANSFORM_NAME

# Build with
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_RANDOM_DEVICE),"")
STRONGSWAN_CONF_OPT += --with-random-device=$(BR2_PACKAGE_STRONGSWAN_WITH_RANDOM_DEVICE)
endif #BR2_PACKAGE_STRONGSWAN_WITH_RANDOM_DEVICE
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_URANDOM_DEVICE),"")
STRONGSWAN_CONF_OPT += --with-urandom-device=$(BR2_PACKAGE_STRONGSWAN_WITH_URANDOM_DEVICE)
endif #BR2_PACKAGE_STRONGSWAN_WITH_URANDOM_DEVICE
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_STRONGSWAN_CONF),"")
STRONGSWAN_CONF_OPT += --with-strongswan-conf=$(BR2_PACKAGE_STRONGSWAN_WITH_STRONGSWAN_CONF)
endif #BR2_PACKAGE_STRONGSWAN_WITH_STRONGSWAN_CONF
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_RESOLV_CONF),"")
STRONGSWAN_CONF_OPT += --with-resolv-conf=$(BR2_PACKAGE_STRONGSWAN_WITH_RESOLV_CONF)
endif #BR2_PACKAGE_STRONGSWAN_WITH_RESOLV_CONF
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_PIDDIR),"")
STRONGSWAN_CONF_OPT += --with-piddir=$(BR2_PACKAGE_STRONGSWAN_WITH_PIDDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_PIDDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_IPSECDIR),"")
STRONGSWAN_CONF_OPT += --with-ipsecdir=$(BR2_PACKAGE_STRONGSWAN_WITH_IPSECDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_IPSECDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_IPSECLIBDIR),"")
STRONGSWAN_CONF_OPT += --with-ipseclibdir=$(BR2_PACKAGE_STRONGSWAN_WITH_IPSECLIBDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_IPSECLIBDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_PLUGINDIR),"")
STRONGSWAN_CONF_OPT += --with-plugindir=$(BR2_PACKAGE_STRONGSWAN_WITH_PLUGINDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_PLUGINDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_IMCVDIR),"")
STRONGSWAN_CONF_OPT += --with-imcvdir=$(BR2_PACKAGE_STRONGSWAN_WITH_IMCVDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_IMCVDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_NM_CA_DIR),"")
STRONGSWAN_CONF_OPT += --with-nm-ca-dir=$(BR2_PACKAGE_STRONGSWAN_WITH_NM_CA_DIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_NM_CA_DIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_SWANCTLDIR),"")
STRONGSWAN_CONF_OPT += --with-swanctldir=$(BR2_PACKAGE_STRONGSWAN_WITH_SWANCTLDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_SWANCTLDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_LINUX_HEADERS),"")
STRONGSWAN_CONF_OPT += --with-linux-headers=$(BR2_PACKAGE_STRONGSWAN_WITH_LINUX_HEADERS)
endif #BR2_PACKAGE_STRONGSWAN_WITH_LINUX_HEADERS
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE),"")
STRONGSWAN_CONF_OPT += --with-routing-table=$(BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE)
endif #BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE_PRIO),"")
STRONGSWAN_CONF_OPT += --with-routing-table-prio=$(BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE_PRIO)
endif #BR2_PACKAGE_STRONGSWAN_WITH_ROUTING_TABLE_PRIO
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_IPSEC_SCRIPT),"")
STRONGSWAN_CONF_OPT += --with-ipsec-script=$(BR2_PACKAGE_STRONGSWAN_WITH_IPSEC_SCRIPT)
endif #BR2_PACKAGE_STRONGSWAN_WITH_IPSEC_SCRIPT
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_FIPS_MODE),"")
STRONGSWAN_CONF_OPT += --with-fips-mode=$(BR2_PACKAGE_STRONGSWAN_WITH_FIPS_MODE)
endif #BR2_PACKAGE_STRONGSWAN_WITH_FIPS_MODE
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_LIBFUZZER),"")
STRONGSWAN_CONF_OPT += --with-libfuzzer=$(BR2_PACKAGE_STRONGSWAN_WITH_LIBFUZZER)
endif #BR2_PACKAGE_STRONGSWAN_WITH_LIBFUZZER
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_CAPABILITIES),"")
STRONGSWAN_CONF_OPT += --with-capabilities=$(BR2_PACKAGE_STRONGSWAN_WITH_CAPABILITIES)
endif #BR2_PACKAGE_STRONGSWAN_WITH_CAPABILITIES
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_MPZ_POWM_SEC),"")
STRONGSWAN_CONF_OPT += --with-mpz_powm_sec=$(BR2_PACKAGE_STRONGSWAN_WITH_MPZ_POWM_SEC)
endif #BR2_PACKAGE_STRONGSWAN_WITH_MPZ_POWM_SEC
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_DEV_HEADERS),"")
STRONGSWAN_CONF_OPT += --with-dev-headers=$(BR2_PACKAGE_STRONGSWAN_WITH_DEV_HEADERS)
endif #BR2_PACKAGE_STRONGSWAN_WITH_DEV_HEADERS
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_PRINTF_HOOKS),"")
STRONGSWAN_CONF_OPT += --with-printf-hooks=$(BR2_PACKAGE_STRONGSWAN_WITH_PRINTF_HOOKS)
endif #BR2_PACKAGE_STRONGSWAN_WITH_PRINTF_HOOKS
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_RUBYGEMDIR),"")
STRONGSWAN_CONF_OPT += --with-rubygemdir=$(BR2_PACKAGE_STRONGSWAN_WITH_RUBYGEMDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_RUBYGEMDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_PYTHONEGGDIR),"")
STRONGSWAN_CONF_OPT += --with-pythoneggdir=$(BR2_PACKAGE_STRONGSWAN_WITH_PYTHONEGGDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_PYTHONEGGDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_SYSTEMDSYSTEMUNITDIR),"")
STRONGSWAN_CONF_OPT += --with-systemdsystemunitdir=$(BR2_PACKAGE_STRONGSWAN_WITH_SYSTEMDSYSTEMUNITDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_SYSTEMDSYSTEMUNITDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_DBUSPOLICYDIR),"")
STRONGSWAN_CONF_OPT += --with-dbuspolicydir=$(BR2_PACKAGE_STRONGSWAN_WITH_DBUSPOLICYDIR)
endif #BR2_PACKAGE_STRONGSWAN_WITH_DBUSPOLICYDIR
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_USER),"")
STRONGSWAN_CONF_OPT += --with-user=$(BR2_PACKAGE_STRONGSWAN_WITH_USER)
endif #BR2_PACKAGE_STRONGSWAN_WITH_USER
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_GROUP),"")
STRONGSWAN_CONF_OPT += --with-group=$(BR2_PACKAGE_STRONGSWAN_WITH_GROUP)
endif #BR2_PACKAGE_STRONGSWAN_WITH_GROUP
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_CHARON_UDP_PORT),"")
STRONGSWAN_CONF_OPT += --with-charon-udp-port=$(BR2_PACKAGE_STRONGSWAN_WITH_CHARON_UDP_PORT)
endif #BR2_PACKAGE_STRONGSWAN_WITH_CHARON_UDP_PORT
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_CHARON_NATT_PORT),"")
STRONGSWAN_CONF_OPT += --with-charon-natt-port=$(BR2_PACKAGE_STRONGSWAN_WITH_CHARON_NATT_PORT)
endif #BR2_PACKAGE_STRONGSWAN_WITH_CHARON_NATT_PORT
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_LIB_PREFIX),"")
STRONGSWAN_CONF_OPT += --with-lib-prefix=$(BR2_PACKAGE_STRONGSWAN_WITH_LIB_PREFIX)
endif #BR2_PACKAGE_STRONGSWAN_WITH_LIB_PREFIX
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_GNU_LD),"")
STRONGSWAN_CONF_OPT += --with-gnu-ld=$(BR2_PACKAGE_STRONGSWAN_WITH_GNU_LD)
endif #BR2_PACKAGE_STRONGSWAN_WITH_GNU_LD
ifneq ($(BR2_PACKAGE_STRONGSWAN_WITH_SYSROOT),"")
STRONGSWAN_CONF_OPT += --with-sysroot=$(BR2_PACKAGE_STRONGSWAN_WITH_SYSROOT)
endif #BR2_PACKAGE_STRONGSWAN_WITH_SYSROOT

# Arch
ifeq ($(BR2_PACKAGE_STRONGSWAN_KEYCHAIN),y)
STRONGSWAN_CONF_OPT += --enable-keychain=yes
endif #BR2_PACKAGE_STRONGSWAN_KEYCHAIN
ifeq ($(BR2_PACKAGE_STRONGSWAN_OSX_ATTR),y)
STRONGSWAN_CONF_OPT += --enable-osx-attr=yes
endif #BR2_PACKAGE_STRONGSWAN_OSX_ATTR
ifeq ($(BR2_PACKAGE_STRONGSWAN_UNITY),y)
STRONGSWAN_CONF_OPT += --enable-unity=yes
endif #BR2_PACKAGE_STRONGSWAN_UNITY
ifeq ($(BR2_PACKAGE_STRONGSWAN_AESNI),y)
STRONGSWAN_CONF_OPT += --enable-aesni=yes
endif #BR2_PACKAGE_STRONGSWAN_AESNI
ifeq ($(BR2_PACKAGE_STRONGSWAN_RDRAND),y)
STRONGSWAN_CONF_OPT += --enable-rdrand=yes
endif #BR2_PACKAGE_STRONGSWAN_RDRAND
ifeq ($(BR2_PACKAGE_STRONGSWAN_WINHTTP),y)
STRONGSWAN_CONF_OPT += --enable-winhttp=yes
endif #BR2_PACKAGE_STRONGSWAN_WINHTTP
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_IPH),y)
STRONGSWAN_CONF_OPT += --enable-kernel-iph=yes
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_IPH
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_WFP),y)
STRONGSWAN_CONF_OPT += --enable-kernel-wfp=yes
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_WFP
ifeq ($(BR2_PACKAGE_STRONGSWAN_SOCKET_WIN),y)
STRONGSWAN_CONF_OPT += --enable-socket-win=yes
endif #BR2_PACKAGE_STRONGSWAN_SOCKET_WIN
ifeq ($(BR2_PACKAGE_STRONGSWAN_SVC),y)
STRONGSWAN_CONF_OPT += --enable-svc=yes
endif #BR2_PACKAGE_STRONGSWAN_SVC
ifeq ($(BR2_PACKAGE_STRONGSWAN_UCI),y)
STRONGSWAN_CONF_OPT += --enable-uci=yes
endif #BR2_PACKAGE_STRONGSWAN_UCI

# Crypto
# CryptoBackend: Openssl/Libgmp/Grypto/Botan/Wolfssl/Padlock
ifeq ($(BR2_PACKAGE_STRONGSWAN_OPENSSL),y)
STRONGSWAN_CONF_OPT += --enable-openssl=yes
endif #BR2_PACKAGE_STRONGSWAN_OPENSSL
ifeq ($(BR2_PACKAGE_STRONGSWAN_GMP),y)
STRONGSWAN_CONF_OPT += --enable-gmp=yes
endif #BR2_PACKAGE_STRONGSWAN_GMP
ifeq ($(BR2_PACKAGE_STRONGSWAN_GCRYPT),y)
STRONGSWAN_CONF_OPT += --enable-gcrypt=yes
endif #BR2_PACKAGE_STRONGSWAN_GCRYPT
ifeq ($(BR2_PACKAGE_STRONGSWAN_BOTAN),y)
STRONGSWAN_CONF_OPT += --enable-botan=yes
endif #BR2_PACKAGE_STRONGSWAN_BOTAN
ifeq ($(BR2_PACKAGE_STRONGSWAN_WOLFSSL),y)
STRONGSWAN_CONF_OPT += --enable-wolfssl=yes
endif #BR2_PACKAGE_STRONGSWAN_WOLFSSL
ifeq ($(BR2_PACKAGE_STRONGSWAN_PADLOCK),y)
STRONGSWAN_CONF_OPT += --enable-padlock=yes
endif #BR2_PACKAGE_STRONGSWAN_PADLOCK

ifeq ($(BR2_PACKAGE_STRONGSWAN_AES),y)
STRONGSWAN_CONF_OPT += --enable-aes
endif #BR2_PACKAGE_STRONGSWAN_AES
ifeq ($(BR2_PACKAGE_STRONGSWAN_AF_ALG),y)
STRONGSWAN_CONF_OPT += --enable-af-alg
endif #BR2_PACKAGE_STRONGSWAN_AF_ALG
ifeq ($(BR2_PACKAGE_STRONGSWAN_BLISS),y)
STRONGSWAN_CONF_OPT += --enable-bliss
endif #BR2_PACKAGE_STRONGSWAN_BLISS
ifeq ($(BR2_PACKAGE_STRONGSWAN_BLOWFISH),y)
STRONGSWAN_CONF_OPT += --enable-blowfish
endif #BR2_PACKAGE_STRONGSWAN_BLOWFISH
ifeq ($(BR2_PACKAGE_STRONGSWAN_CCM),y)
STRONGSWAN_CONF_OPT += --enable-ccm
endif #BR2_PACKAGE_STRONGSWAN_CCM
ifeq ($(BR2_PACKAGE_STRONGSWAN_CHAPOLY),y)
STRONGSWAN_CONF_OPT += --enable-chapoly
endif #BR2_PACKAGE_STRONGSWAN_CHAPOLY
ifeq ($(BR2_PACKAGE_STRONGSWAN_CMAC),y)
STRONGSWAN_CONF_OPT += --enable-cmac
endif #BR2_PACKAGE_STRONGSWAN_CMAC
ifeq ($(BR2_PACKAGE_STRONGSWAN_CTR),y)
STRONGSWAN_CONF_OPT += --enable-ctr
endif #BR2_PACKAGE_STRONGSWAN_CTR
ifeq ($(BR2_PACKAGE_STRONGSWAN_CURVE25519),y)
STRONGSWAN_CONF_OPT += --enable-curve25519
endif #BR2_PACKAGE_STRONGSWAN_CURVE25519
ifeq ($(BR2_PACKAGE_STRONGSWAN_DES),y)
STRONGSWAN_CONF_OPT += --enable-des
endif #BR2_PACKAGE_STRONGSWAN_DES
ifeq ($(BR2_PACKAGE_STRONGSWAN_DRBG),y)
STRONGSWAN_CONF_OPT += --enable-drbg
endif #BR2_PACKAGE_STRONGSWAN_DRBG
ifeq ($(BR2_PACKAGE_STRONGSWAN_GCM),y)
STRONGSWAN_CONF_OPT += --enable-gcm
endif #BR2_PACKAGE_STRONGSWAN_GCM
ifeq ($(BR2_PACKAGE_STRONGSWAN_HMAC),y)
STRONGSWAN_CONF_OPT += --enable-hmac
endif #BR2_PACKAGE_STRONGSWAN_HMAC
ifeq ($(BR2_PACKAGE_STRONGSWAN_MD4),y)
STRONGSWAN_CONF_OPT += --enable-md4
endif #BR2_PACKAGE_STRONGSWAN_MD4
ifeq ($(BR2_PACKAGE_STRONGSWAN_MD5),y)
STRONGSWAN_CONF_OPT += --enable-md5
endif #BR2_PACKAGE_STRONGSWAN_MD5
ifeq ($(BR2_PACKAGE_STRONGSWAN_MGF1),y)
STRONGSWAN_CONF_OPT += --enable-mgf1
endif #BR2_PACKAGE_STRONGSWAN_MGF1
ifeq ($(BR2_PACKAGE_STRONGSWAN_NEWHOPE),y)
STRONGSWAN_CONF_OPT += --enable-newhope
endif #BR2_PACKAGE_STRONGSWAN_NEWHOPE
ifeq ($(BR2_PACKAGE_STRONGSWAN_NONCE),y)
STRONGSWAN_CONF_OPT += --enable-nonce
endif #BR2_PACKAGE_STRONGSWAN_NONCE
ifeq ($(BR2_PACKAGE_STRONGSWAN_NTRU),y)
STRONGSWAN_CONF_OPT += --enable-ntru
endif #BR2_PACKAGE_STRONGSWAN_NTRU
ifeq ($(BR2_PACKAGE_STRONGSWAN_RANDOM),y)
STRONGSWAN_CONF_OPT += --enable-random
endif #BR2_PACKAGE_STRONGSWAN_RANDOM
ifeq ($(BR2_PACKAGE_STRONGSWAN_RC2),y)
STRONGSWAN_CONF_OPT += --enable-rc2
endif #BR2_PACKAGE_STRONGSWAN_RC2
ifeq ($(BR2_PACKAGE_STRONGSWAN_SHA1),y)
STRONGSWAN_CONF_OPT += --enable-sha1
endif #BR2_PACKAGE_STRONGSWAN_SHA1
ifeq ($(BR2_PACKAGE_STRONGSWAN_SHA2),y)
STRONGSWAN_CONF_OPT += --enable-sha2
endif #BR2_PACKAGE_STRONGSWAN_SHA2
ifeq ($(BR2_PACKAGE_STRONGSWAN_SHA3),y)
STRONGSWAN_CONF_OPT += --enable-sha3
endif #BR2_PACKAGE_STRONGSWAN_SHA3
ifeq ($(BR2_PACKAGE_STRONGSWAN_XCBC),y)
STRONGSWAN_CONF_OPT += --enable-xcbc
endif #BR2_PACKAGE_STRONGSWAN_XCBC

# PKI
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKI),y)
STRONGSWAN_CONF_OPT += --enable-pki=yes
endif #BR2_PACKAGE_STRONGSWAN_PKI
ifeq ($(BR2_PACKAGE_STRONGSWAN_TKM),y)
STRONGSWAN_CONF_OPT += --enable-tkm=yes
endif #BR2_PACKAGE_STRONGSWAN_TKM
ifeq ($(BR2_PACKAGE_STRONGSWAN_ACERT),y)
STRONGSWAN_CONF_OPT += --enable-acert=yes
endif #BR2_PACKAGE_STRONGSWAN_ACERT
ifeq ($(BR2_PACKAGE_STRONGSWAN_AGENT),y)
STRONGSWAN_CONF_OPT += --enable-agent=yes
endif #BR2_PACKAGE_STRONGSWAN_AGENT
ifeq ($(BR2_PACKAGE_STRONGSWAN_CONSTRAINTS),y)
STRONGSWAN_CONF_OPT += --enable-constraints=yes
endif #BR2_PACKAGE_STRONGSWAN_CONSTRAINTS
ifeq ($(BR2_PACKAGE_STRONGSWAN_DNSKEY),y)
STRONGSWAN_CONF_OPT += --enable-dnskey=yes
endif #BR2_PACKAGE_STRONGSWAN_DNSKEY
ifeq ($(BR2_PACKAGE_STRONGSWAN_PEM),y)
STRONGSWAN_CONF_OPT += --enable-pem=yes
endif #BR2_PACKAGE_STRONGSWAN_PEM
ifeq ($(BR2_PACKAGE_STRONGSWAN_PGP),y)
STRONGSWAN_CONF_OPT += --enable-pgp=yes
endif #BR2_PACKAGE_STRONGSWAN_PGP
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKCS1),y)
STRONGSWAN_CONF_OPT += --enable-pkcs1=yes
endif #BR2_PACKAGE_STRONGSWAN_PKCS1
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKCS7),y)
STRONGSWAN_CONF_OPT += --enable-pkcs7=yes
endif #BR2_PACKAGE_STRONGSWAN_PKCS7
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKCS8),y)
STRONGSWAN_CONF_OPT += --enable-pkcs8=yes
endif #BR2_PACKAGE_STRONGSWAN_PKCS8
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKCS11),y)
STRONGSWAN_CONF_OPT += --enable-pkcs11=yes
endif #BR2_PACKAGE_STRONGSWAN_PKCS11
ifeq ($(BR2_PACKAGE_STRONGSWAN_PKCS12),y)
STRONGSWAN_CONF_OPT += --enable-pkcs12=yes
endif #BR2_PACKAGE_STRONGSWAN_PKCS12
ifeq ($(BR2_PACKAGE_STRONGSWAN_PUBKEY),y)
STRONGSWAN_CONF_OPT += --enable-pubkey=yes
endif #BR2_PACKAGE_STRONGSWAN_PUBKEY
ifeq ($(BR2_PACKAGE_STRONGSWAN_REVOCATION),y)
STRONGSWAN_CONF_OPT += --enable-revocation=yes
endif #BR2_PACKAGE_STRONGSWAN_REVOCATION
ifeq ($(BR2_PACKAGE_STRONGSWAN_SSHKEY),y)
STRONGSWAN_CONF_OPT += --enable-sshkey=yes
endif #BR2_PACKAGE_STRONGSWAN_SSHKEY
ifeq ($(BR2_PACKAGE_STRONGSWAN_X509),y)
STRONGSWAN_CONF_OPT += --enable-x509=yes
endif #BR2_PACKAGE_STRONGSWAN_X509
ifeq ($(BR2_PACKAGE_STRONGSWAN_ADDRBLOCK),y)
STRONGSWAN_CONF_OPT += --enable-addrblock=yes
endif #BR2_PACKAGE_STRONGSWAN_ADDRBLOCK
ifeq ($(BR2_PACKAGE_STRONGSWAN_CERTEXPIRE),y)
STRONGSWAN_CONF_OPT += --enable-certexpire=yes
endif #BR2_PACKAGE_STRONGSWAN_CERTEXPIRE
ifeq ($(BR2_PACKAGE_STRONGSWAN_COUPLING),y)
STRONGSWAN_CONF_OPT += --enable-coupling=yes
endif #BR2_PACKAGE_STRONGSWAN_COUPLING
ifeq ($(BR2_PACKAGE_STRONGSWAN_DNSCERT),y)
STRONGSWAN_CONF_OPT += --enable-dnscert=yes
endif #BR2_PACKAGE_STRONGSWAN_DNSCERT
ifeq ($(BR2_PACKAGE_STRONGSWAN_SYSTIME_FIX),y)
STRONGSWAN_CONF_OPT += --enable-systime-fix=yes
endif #BR2_PACKAGE_STRONGSWAN_SYSTIME_FIX
ifeq ($(BR2_PACKAGE_STRONGSWAN_TPM),y)
STRONGSWAN_CONF_OPT += --enable-tpm=yes
endif #BR2_PACKAGE_STRONGSWAN_TPM
ifeq ($(BR2_PACKAGE_STRONGSWAN_AIKGEN),y)
STRONGSWAN_CONF_OPT += --enable-aikgen=yes
endif #BR2_PACKAGE_STRONGSWAN_AIKGEN

#EAP/802.1x
ifeq ($(BR2_PACKAGE_STRONGSWAN_FIPS_PRF),y)
STRONGSWAN_CONF_OPT += --enable-fips-prf
endif #BR2_PACKAGE_STRONGSWAN_FIPS_PRF
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIM),y)
STRONGSWAN_CONF_OPT += --enable-eap-sim
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIM
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIM_FILE),y)
STRONGSWAN_CONF_OPT += --enable-eap-sim-file
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIM_FILE
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIM_PCSC),y)
STRONGSWAN_CONF_OPT += --enable-eap-sim-pcsc
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIM_PCSC
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_AKA),y)
STRONGSWAN_CONF_OPT += --enable-eap-aka
endif #BR2_PACKAGE_STRONGSWAN_EAP_AKA
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_AKA_3GPP),y)
STRONGSWAN_CONF_OPT += --enable-eap-aka-3gpp
endif #BR2_PACKAGE_STRONGSWAN_EAP_AKA_3GPP
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_AKA_3GPP2),y)
STRONGSWAN_CONF_OPT += --enable-eap-aka-3gpp2
endif #BR2_PACKAGE_STRONGSWAN_EAP_AKA_3GPP2
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_SQL),y)
STRONGSWAN_CONF_OPT += --enable-eap-simaka-sql
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_SQL
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_PSEUDONYM),y)
STRONGSWAN_CONF_OPT += --enable-eap-simaka-pseudonym
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_PSEUDONYM
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_REAUTH),y)
STRONGSWAN_CONF_OPT += --enable-eap-simaka-reauth
endif #BR2_PACKAGE_STRONGSWAN_EAP_SIMAKA_REAUTH
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_IDENTITY),y)
STRONGSWAN_CONF_OPT += --enable-eap-identity
endif #BR2_PACKAGE_STRONGSWAN_EAP_IDENTITY
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_MD5),y)
STRONGSWAN_CONF_OPT += --enable-eap-md5
endif #BR2_PACKAGE_STRONGSWAN_EAP_MD5
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_GTC),y)
STRONGSWAN_CONF_OPT += --enable-eap-gtc
endif #BR2_PACKAGE_STRONGSWAN_EAP_GTC
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_MSCHAPV2),y)
STRONGSWAN_CONF_OPT += --enable-eap-mschapv2
endif #BR2_PACKAGE_STRONGSWAN_EAP_MSCHAPV2
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_TLS),y)
STRONGSWAN_CONF_OPT += --enable-eap-tls
endif #BR2_PACKAGE_STRONGSWAN_EAP_TLS
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_TTLS),y)
STRONGSWAN_CONF_OPT += --enable-eap-ttls
endif #BR2_PACKAGE_STRONGSWAN_EAP_TTLS
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_PEAP),y)
STRONGSWAN_CONF_OPT += --enable-eap-peap
endif #BR2_PACKAGE_STRONGSWAN_EAP_PEAP
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_TNC),y)
STRONGSWAN_CONF_OPT += --enable-eap-tnc
endif #BR2_PACKAGE_STRONGSWAN_EAP_TNC
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_DYNAMIC),y)
STRONGSWAN_CONF_OPT += --enable-eap-dynamic
endif #BR2_PACKAGE_STRONGSWAN_EAP_DYNAMIC
ifeq ($(BR2_PACKAGE_STRONGSWAN_EAP_RADIUS),y)
STRONGSWAN_CONF_OPT += --enable-eap-radius
endif #BR2_PACKAGE_STRONGSWAN_EAP_RADIUS
ifeq ($(BR2_PACKAGE_STRONGSWAN_XAUth_EAP),y)
STRONGSWAN_CONF_OPT += --enable-xauth-eap
endif #BR2_PACKAGE_STRONGSWAN_XAUth_EAP

#TNC/IMC/IMV
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNC_IFMAP),y)
STRONGSWAN_CONF_OPT += --enable-tnc-ifmap
endif #BR2_PACKAGE_STRONGSWAN_TNC_IFMAP
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNC_PDP),y)
STRONGSWAN_CONF_OPT += --enable-tnc-pdp
endif #BR2_PACKAGE_STRONGSWAN_TNC_PDP
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNC_IMC),y)
STRONGSWAN_CONF_OPT += --enable-tnc-imc
endif #BR2_PACKAGE_STRONGSWAN_TNC_IMC
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNC_IMV),y)
STRONGSWAN_CONF_OPT += --enable-tnc-imv
endif #BR2_PACKAGE_STRONGSWAN_TNC_IMV
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNCCS_11),y)
STRONGSWAN_CONF_OPT += --enable-tnccs-11
endif #BR2_PACKAGE_STRONGSWAN_TNCCS_11
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNCCS_20),y)
STRONGSWAN_CONF_OPT += --enable-tnccs-20
endif #BR2_PACKAGE_STRONGSWAN_TNCCS_20
ifeq ($(BR2_PACKAGE_STRONGSWAN_TNCCS_DYNAMIC),y)
STRONGSWAN_CONF_OPT += --enable-tnccs-dynamic
endif #BR2_PACKAGE_STRONGSWAN_TNCCS_DYNAMIC
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_TEST),y)
STRONGSWAN_CONF_OPT += --enable-imc-test
endif #BR2_PACKAGE_STRONGSWAN_IMC_TEST
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_TEST),y)
STRONGSWAN_CONF_OPT += --enable-imv-test
endif #BR2_PACKAGE_STRONGSWAN_IMV_TEST
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_SCANNER),y)
STRONGSWAN_CONF_OPT += --enable-imc-scanner
endif #BR2_PACKAGE_STRONGSWAN_IMC_SCANNER
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_SCANNER),y)
STRONGSWAN_CONF_OPT += --enable-imv-scanner
endif #BR2_PACKAGE_STRONGSWAN_IMV_SCANNER
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_OS),y)
STRONGSWAN_CONF_OPT += --enable-imc-os
endif #BR2_PACKAGE_STRONGSWAN_IMC_OS
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_OS),y)
STRONGSWAN_CONF_OPT += --enable-imv-os
endif #BR2_PACKAGE_STRONGSWAN_IMV_OS
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_ATTESTATION),y)
STRONGSWAN_CONF_OPT += --enable-imc-attestation
endif #BR2_PACKAGE_STRONGSWAN_IMC_ATTESTATION
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_ATTESTATION),y)
STRONGSWAN_CONF_OPT += --enable-imv-attestation
endif #BR2_PACKAGE_STRONGSWAN_IMV_ATTESTATION
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_SWIMA),y)
STRONGSWAN_CONF_OPT += --enable-imc-swima
endif #BR2_PACKAGE_STRONGSWAN_IMC_SWIMA
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_SWIMA),y)
STRONGSWAN_CONF_OPT += --enable-imv-swima
endif #BR2_PACKAGE_STRONGSWAN_IMV_SWIMA
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMC_HCD),y)
STRONGSWAN_CONF_OPT += --enable-imc-hcd
endif #BR2_PACKAGE_STRONGSWAN_IMC_HCD
ifeq ($(BR2_PACKAGE_STRONGSWAN_IMV_HCD),y)
STRONGSWAN_CONF_OPT += --enable-imv-hcd
endif #BR2_PACKAGE_STRONGSWAN_IMV_HCD

#Other
ifeq ($(BR2_PACKAGE_STRONGSWAN_CURL),y)
STRONGSWAN_CONF_OPT += --enable-curl
endif #BR2_PACKAGE_STRONGSWAN_CURL
ifeq ($(BR2_PACKAGE_STRONGSWAN_FILES),y)
STRONGSWAN_CONF_OPT += --enable-files
endif #BR2_PACKAGE_STRONGSWAN_FILES
ifeq ($(BR2_PACKAGE_STRONGSWAN_LDAP),y)
STRONGSWAN_CONF_OPT += --enable-ldap
endif #BR2_PACKAGE_STRONGSWAN_LDAP
ifeq ($(BR2_PACKAGE_STRONGSWAN_SOUP),y)
STRONGSWAN_CONF_OPT += --enable-soup
endif #BR2_PACKAGE_STRONGSWAN_SOUP
ifeq ($(BR2_PACKAGE_STRONGSWAN_UNBOUND),y)
STRONGSWAN_CONF_OPT += --enable-unbound
endif #BR2_PACKAGE_STRONGSWAN_UNBOUND
ifeq ($(BR2_PACKAGE_STRONGSWAN_ANDROID_DNS),y)
STRONGSWAN_CONF_OPT += --enable-android-dns
endif #BR2_PACKAGE_STRONGSWAN_ANDROID_DNS
ifeq ($(BR2_PACKAGE_STRONGSWAN_ANDROID_LOG),y)
STRONGSWAN_CONF_OPT += --enable-android-log
endif #BR2_PACKAGE_STRONGSWAN_ANDROID_LOG
ifeq ($(BR2_PACKAGE_STRONGSWAN_ATTR),y)
STRONGSWAN_CONF_OPT += --enable-attr
endif #BR2_PACKAGE_STRONGSWAN_ATTR
ifeq ($(BR2_PACKAGE_STRONGSWAN_ATTR_SQL),y)
STRONGSWAN_CONF_OPT += --enable-attr-sql
endif #BR2_PACKAGE_STRONGSWAN_ATTR_SQL
ifeq ($(BR2_PACKAGE_STRONGSWAN_BYPASS_LAN),y)
STRONGSWAN_CONF_OPT += --enable-bypass-lan
endif #BR2_PACKAGE_STRONGSWAN_BYPASS_LAN
ifeq ($(BR2_PACKAGE_STRONGSWAN_COUNTERS),y)
STRONGSWAN_CONF_OPT += --enable-counters
endif #BR2_PACKAGE_STRONGSWAN_COUNTERS
ifeq ($(BR2_PACKAGE_STRONGSWAN_DHCP),y)
STRONGSWAN_CONF_OPT += --enable-dhcp
endif #BR2_PACKAGE_STRONGSWAN_DHCP
ifeq ($(BR2_PACKAGE_STRONGSWAN_CONNMARK),y)
STRONGSWAN_CONF_OPT += --enable-connmark
endif #BR2_PACKAGE_STRONGSWAN_CONNMARK
ifeq ($(BR2_PACKAGE_STRONGSWAN_DUPLICHECK),y)
STRONGSWAN_CONF_OPT += --enable-duplicheck
endif #BR2_PACKAGE_STRONGSWAN_DUPLICHECK
ifeq ($(BR2_PACKAGE_STRONGSWAN_ERROR_NOTIFY),y)
STRONGSWAN_CONF_OPT += --enable-error-notify
endif #BR2_PACKAGE_STRONGSWAN_ERROR_NOTIFY
ifeq ($(BR2_PACKAGE_STRONGSWAN_FARP),y)
STRONGSWAN_CONF_OPT += --enable-farp
endif #BR2_PACKAGE_STRONGSWAN_FARP
ifeq ($(BR2_PACKAGE_STRONGSWAN_FORECAST),y)
STRONGSWAN_CONF_OPT += --enable-forecast
endif #BR2_PACKAGE_STRONGSWAN_FORECAST
ifeq ($(BR2_PACKAGE_STRONGSWAN_HA),y)
STRONGSWAN_CONF_OPT += --enable-ha
endif #BR2_PACKAGE_STRONGSWAN_HA
ifeq ($(BR2_PACKAGE_STRONGSWAN_IPSECKEY),y)
STRONGSWAN_CONF_OPT += --enable-ipseckey
endif #BR2_PACKAGE_STRONGSWAN_IPSECKEY
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_LIBIPSEC),y)
STRONGSWAN_CONF_OPT += --enable-kernel-libipsec
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_LIBIPSEC
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_NETLINK),y)
STRONGSWAN_CONF_OPT += --enable-kernel-netlink
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_NETLINK
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_PFKEY),y)
STRONGSWAN_CONF_OPT += --enable-kernel-pfkey
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_PFKEY
ifeq ($(BR2_PACKAGE_STRONGSWAN_KERNEL_PFROUTE),y)
STRONGSWAN_CONF_OPT += --enable-kernel-pfroute
endif #BR2_PACKAGE_STRONGSWAN_KERNEL_PFROUTE
ifeq ($(BR2_PACKAGE_STRONGSWAN_LED),y)
STRONGSWAN_CONF_OPT += --enable-led
endif #BR2_PACKAGE_STRONGSWAN_LED
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOOKIP),y)
STRONGSWAN_CONF_OPT += --enable-lookip
endif #BR2_PACKAGE_STRONGSWAN_LOOKIP
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOAD_TESTER),y)
STRONGSWAN_CONF_OPT += --enable-load-tester
endif #BR2_PACKAGE_STRONGSWAN_LOAD_TESTER
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOAD_TESTER),y)
STRONGSWAN_CONF_OPT += --enable-load-tester
endif #BR2_PACKAGE_STRONGSWAN_LOAD_TESTER
ifeq ($(BR2_PACKAGE_STRONGSWAN_MEDIATION),y)
STRONGSWAN_CONF_OPT += --enable-mediation
endif #BR2_PACKAGE_STRONGSWAN_MEDIATION
ifeq ($(BR2_PACKAGE_STRONGSWAN_MEDCLI),y)
STRONGSWAN_CONF_OPT += --enable-medcli
endif #BR2_PACKAGE_STRONGSWAN_MEDCLI
ifeq ($(BR2_PACKAGE_STRONGSWAN_MEDSRV),y)
STRONGSWAN_CONF_OPT += --enable-medsrv
endif #BR2_PACKAGE_STRONGSWAN_MEDSRV
ifeq ($(BR2_PACKAGE_STRONGSWAN_MYSQL),y)
STRONGSWAN_CONF_OPT += --enable-mysql
endif #BR2_PACKAGE_STRONGSWAN_MYSQL
ifeq ($(BR2_PACKAGE_STRONGSWAN_P_CSCF),y)
STRONGSWAN_CONF_OPT += --enable-p-cscf
endif #BR2_PACKAGE_STRONGSWAN_P_CSCF
ifeq ($(BR2_PACKAGE_STRONGSWAN_RADATTR),y)
STRONGSWAN_CONF_OPT += --enable-radattr
endif #BR2_PACKAGE_STRONGSWAN_RADATTR
ifeq ($(BR2_PACKAGE_STRONGSWAN_RESOLVE),y)
STRONGSWAN_CONF_OPT += --enable-resolve
endif #BR2_PACKAGE_STRONGSWAN_RESOLVE
ifeq ($(BR2_PACKAGE_STRONGSWAN_SAVE_KEYS),y)
STRONGSWAN_CONF_OPT += --enable-save-keys
endif #BR2_PACKAGE_STRONGSWAN_SAVE_KEYS
ifeq ($(BR2_PACKAGE_STRONGSWAN_SMP),y)
STRONGSWAN_CONF_OPT += --enable-smp
endif #BR2_PACKAGE_STRONGSWAN_SMP
ifeq ($(BR2_PACKAGE_STRONGSWAN_SOCKET_DEFAULT),y)
STRONGSWAN_CONF_OPT += --enable-socket-default
endif #BR2_PACKAGE_STRONGSWAN_SOCKET_DEFAULT
ifeq ($(BR2_PACKAGE_STRONGSWAN_SOCKET_DYNAMIC),y)
STRONGSWAN_CONF_OPT += --enable-socket-dynamic
endif #BR2_PACKAGE_STRONGSWAN_SOCKET_DYNAMIC
ifeq ($(BR2_PACKAGE_STRONGSWAN_SQL),y)
STRONGSWAN_CONF_OPT += --enable-sql
endif #BR2_PACKAGE_STRONGSWAN_SQL
ifeq ($(BR2_PACKAGE_STRONGSWAN_SQLITE),y)
STRONGSWAN_CONF_OPT += --enable-sqlite
endif #BR2_PACKAGE_STRONGSWAN_SQLITE
ifeq ($(BR2_PACKAGE_STRONGSWAN_VICI),y)
STRONGSWAN_CONF_OPT += --enable-vici
endif #BR2_PACKAGE_STRONGSWAN_VICI
ifeq ($(BR2_PACKAGE_STRONGSWAN_WHITELIST),y)
STRONGSWAN_CONF_OPT += --enable-whitelist
endif #BR2_PACKAGE_STRONGSWAN_WHITELIST
ifeq ($(BR2_PACKAGE_STRONGSWAN_XAUTH_GENERIC),y)
STRONGSWAN_CONF_OPT += --enable-xauth-generic
endif #BR2_PACKAGE_STRONGSWAN_XAUTH_GENERIC
ifeq ($(BR2_PACKAGE_STRONGSWAN_XAUTH_noauth),y)
STRONGSWAN_CONF_OPT += --enable-xauth-noauth
endif #BR2_PACKAGE_STRONGSWAN_XAUTH_noauth
ifeq ($(BR2_PACKAGE_STRONGSWAN_XAUTH_PAM),y)
STRONGSWAN_CONF_OPT += --enable-xauth-pam
endif #BR2_PACKAGE_STRONGSWAN_XAUTH_PAM
ifeq ($(BR2_PACKAGE_STRONGSWAN_BFD_BACKTRACES),y)
STRONGSWAN_CONF_OPT += --enable-bfd-backtraces
endif #BR2_PACKAGE_STRONGSWAN_BFD_BACKTRACES
ifeq ($(BR2_PACKAGE_STRONGSWAN_COVERAGE),y)
STRONGSWAN_CONF_OPT += --enable-coverage
endif #BR2_PACKAGE_STRONGSWAN_COVERAGE
ifeq ($(BR2_PACKAGE_STRONGSWAN_DBGHELP_BACKTRACES),y)
STRONGSWAN_CONF_OPT += --enable-dbghelp-backtraces
endif #BR2_PACKAGE_STRONGSWAN_DBGHELP_BACKTRACES
ifeq ($(BR2_PACKAGE_STRONGSWAN_DEPENDENCY_TRACKING),y)
STRONGSWAN_CONF_OPT += --enable-dependency-tracking
endif #BR2_PACKAGE_STRONGSWAN_DEPENDENCY_TRACKING
ifeq ($(BR2_PACKAGE_STRONGSWAN_GIT_VERSION),y)
STRONGSWAN_CONF_OPT += --enable-git-version
endif #BR2_PACKAGE_STRONGSWAN_GIT_VERSION
ifeq ($(BR2_PACKAGE_STRONGSWAN_LEAK_DETECTIVE),y)
STRONGSWAN_CONF_OPT += --enable-leak-detective
endif #BR2_PACKAGE_STRONGSWAN_LEAK_DETECTIVE
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOAD_WARNING),y)
STRONGSWAN_CONF_OPT += --enable-load-warning
endif #BR2_PACKAGE_STRONGSWAN_LOAD_WARNING
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOCK_PROFILER),y)
STRONGSWAN_CONF_OPT += --enable-lock-profiler
endif #BR2_PACKAGE_STRONGSWAN_LOCK_PROFILER
ifeq ($(BR2_PACKAGE_STRONGSWAN_LOG_THREAD_IDS),y)
STRONGSWAN_CONF_OPT += --enable-log-thread-ids
endif #BR2_PACKAGE_STRONGSWAN_LOG_THREAD_IDS
ifeq ($(BR2_PACKAGE_STRONGSWAN_TEST_VECTORS),y)
STRONGSWAN_CONF_OPT += --enable-test-vectors
endif #BR2_PACKAGE_STRONGSWAN_TEST_VECTORS
ifeq ($(BR2_PACKAGE_STRONGSWAN_UNWIND_BACKTRACES),y)
STRONGSWAN_CONF_OPT += --enable-unwind-backtraces
endif #BR2_PACKAGE_STRONGSWAN_UNWIND_BACKTRACES
ifeq ($(BR2_PACKAGE_STRONGSWAN_FAST),y)
STRONGSWAN_CONF_OPT += --enable-fast
endif #BR2_PACKAGE_STRONGSWAN_FAST
ifeq ($(BR2_PACKAGE_STRONGSWAN_LIBIPSEC),y)
STRONGSWAN_CONF_OPT += --enable-libipsec
endif #BR2_PACKAGE_STRONGSWAN_LIBIPSEC
ifeq ($(BR2_PACKAGE_STRONGSWAN_RUBY_GEMS),y)
STRONGSWAN_CONF_OPT += --enable-ruby-gems
endif #BR2_PACKAGE_STRONGSWAN_RUBY_GEMS
ifeq ($(BR2_PACKAGE_STRONGSWAN_RUBY_GEMS_INSTALL),y)
STRONGSWAN_CONF_OPT += --enable-ruby-gems-install
endif #BR2_PACKAGE_STRONGSWAN_RUBY_GEMS_INSTALL
ifeq ($(BR2_PACKAGE_STRONGSWAN_PYTHON_EGGS),y)
STRONGSWAN_CONF_OPT += --enable-python-eggs
endif #BR2_PACKAGE_STRONGSWAN_PYTHON_EGGS
ifeq ($(BR2_PACKAGE_STRONGSWAN_PYTHON_EGGS_INSTALL),y)
STRONGSWAN_CONF_OPT += --enable-python-eggs-install
endif #BR2_PACKAGE_STRONGSWAN_PYTHON_EGGS_INSTALL
ifeq ($(BR2_PACKAGE_STRONGSWAN_PERL_CPAN),y)
STRONGSWAN_CONF_OPT += --enable-perl-cpan
endif #BR2_PACKAGE_STRONGSWAN_PERL_CPAN
ifeq ($(BR2_PACKAGE_STRONGSWAN_PERL_CPAN_INSTALL),y)
STRONGSWAN_CONF_OPT += --enable-perl-cpan-install
endif #BR2_PACKAGE_STRONGSWAN_PERL_CPAN_INSTALL
ifeq ($(BR2_PACKAGE_STRONGSWAN_TSS_TROUSERS),y)
STRONGSWAN_CONF_OPT += --enable-tss-trousers
endif #BR2_PACKAGE_STRONGSWAN_TSS_TROUSERS
ifeq ($(BR2_PACKAGE_STRONGSWAN_TSS_TSS2),y)
STRONGSWAN_CONF_OPT += --enable-tss-tss2
endif #BR2_PACKAGE_STRONGSWAN_TSS_TSS2
ifeq ($(BR2_PACKAGE_STRONGSWAN_MONOLITHIC),y)
STRONGSWAN_CONF_OPT += --enable-monolithic
endif #BR2_PACKAGE_STRONGSWAN_MONOLITHIC
endif #BR2_PACKAGE_STRONGSWAN_BUILD_ADVANCED


define STRONGSWAN_CLEANUP_FILES
# clear configuration files from comments and emtpy lines
	find $(TARGET_DIR)/etc/ -maxdepth 3 -type f -name "*\.conf" | grep strongswan |  xargs sed -i '/^$$/d; / *#/d'
endef

STRONGSWAN_POST_INSTALL_TARGET_HOOKS += STRONGSWAN_CLEANUP_FILES

$(eval $(call AUTOTARGETS))
