OBJS = benchmark.o bitbase.o bitboard.o endgame.o \
       evaluate.o main.o material.o misc.o movegen.o \
       movepick.o pawns.o position.o psqt.o search.o \
       thread.o timeman.o tt.o uci.o ucioption.o \
       syzygy/tbprobe.o

default all: stockfish

stockfish: $(OBJS)
	$(CXX) -o $@ $^ $(LDFLAGS)

clean:
	rm -f stockfish $(OBJS)
