9607BOOT_SITE = $(DLINK_GIT_STORAGE)/$(BR2_BOOTLOADER_EXTERNAL_LOCATION)
9607BOOT_VERSION = $(call qstrip,$(BR2_BOOTLOADER_EXTERNAL_BRANCH))

9607BOOT_MAKE_OPTS =
9607BOOT_CFLAGS =

9607BOOT_MAKE_OPTS += CONFIG_DLINK_FW_MAGIC=$(BR2_FW_MAGIC_VERSION)c0ffee
9607BOOT_CFLAGS += -DCONFIG_DLINK_FW_MAGIC=$(BR2_FW_MAGIC_VERSION)c0ffee

ifeq ($(BR2_BOOTLOADER_HTTP_SERVER),y)
BOOTLOADER_HTTP_IP_ADDR = $(call qstrip,$(BR2_BOOTLOADER_HTTP_IP_ADDR))
BOOTLOADER_HTTP_IP_ADDR = 0x$(shell printf "%02x" "$(subst ., ,$(BR2_BOOTLOADER_HTTP_IP_ADDR))")
9607BOOT_MAKE_OPTS += CONFIG_CMD_HTTPD=y CONFIG_CMD_HTTP_IP_ADDR=$(BOOTLOADER_HTTP_IP_ADDR)
9607BOOT_CFLAGS += -DCONFIG_CMD_HTTPD -DCONFIG_CMD_HTTP_IP_ADDR=$(BOOTLOADER_HTTP_IP_ADDR)

ifneq ($(BR2_FW_UUID),)
9607BOOT_MAKE_OPTS += CONFIG_PRIVATE_KEY=y CONFIG_MD5=y CONFIG_DLINK_FW_UUID='\"$(BR2_FW_UUID)\"'
9607BOOT_CFLAGS += -DCONFIG_PRIVATE_KEY -DCONFIG_MD5 -DCONFIG_DLINK_FW_UUID='\"$(BR2_FW_UUID)\"'

ifneq ($(BR2_FW_UUID_SEC),)
9607BOOT_MAKE_OPTS += CONFIG_DLINK_FW_UUID_SEC='\"$(BR2_FW_UUID_SEC)\"'
9607BOOT_CFLAGS += -DCONFIG_DLINK_FW_UUID_SEC='\"$(BR2_FW_UUID_SEC)\"'
endif
endif
endif

9607BOOT_MAKE_OPTS += DLINK_CFLAGS="$(9607BOOT_CFLAGS)"

define 9607BOOT_CONFIGURE_CMDS
	@mkdir -p $(@D)/release
	@echo "CROSS_COMPILE=$(TARGET_CROSS)" > $(@D)/toolkit_path.in
	@echo "OTTO_RELEASE_DIR=$(@D)/release" >> $(@D)/toolkit_path.in
	@ln -s ../toolkit_path.in -t $(@D)/uboot/ -f
	$(MAKE1) -C $(@D) preconfig_$(call qstrip,$(BR2_BOOTLOADER_CONFIG_COMMANDS))
	$(MAKE1) -C $(@D)/uboot preconfig_$(call qstrip,$(BR2_BOOTLOADER_CONFIG_COMMANDS))
endef

define 9607BOOT_BUILD_CMDS
	$(MAKE1) -C $(@D)/uboot $(9607BOOT_MAKE_OPTS) all
	$(MAKE1) -C $(@D) $(9607BOOT_MAKE_OPTS) all
endef

define 9607BOOT_CLEAN_CMDS
	$(MAKE1) -C $(@D)/uboot $(9607BOOT_MAKE_OPTS) clean
	$(MAKE1) -C $(@D) $(9607BOOT_MAKE_OPTS) clean
endef

define 9607BOOT_INSTALL_TARGET_CMDS
endef

$(eval $(call GENTARGETS))
