#!/bin/bash

jsonrpc="{\"id\": 1, \"method\": \"$1\""

if [ -n "$2" ]; then
	jsonrpc="$jsonrpc, \"params\": $2"
fi

jsonrpc="$jsonrpc}"

echo $jsonrpc
dsysctl -u /var/run/sched.sock --raw -- "$jsonrpc"
