# TWAMP_PROTOCOL_SITE_METHOD = git
# TWAMP_PROTOCOL_SITE = https://github.com/emirica/twamp-protocol/archive
TWAMP_PROTOCOL_SITE = $(DLINK_STORAGE)
TWAMP_PROTOCOL_VERSION = 20c550d2a9f2a709bbb9cc0f2e8704203dbcfa46
TWAMP_PROTOCOL_SOURCE = twamp-protocol-$(TWAMP_PROTOCOL_VERSION).tar.gz
TWAMP_PROTOCOL_LICENSE = GPL-2.0-only
TWAMP_PROTOCOL_LICENSE_FILES = LICENSE.txt
TWAMP_PROTOCOL_TARGET_DIR = /usr/sbin
# TWAMP_PROTOCOL_INSTALL_STAGING = YES
# TWAMP_PROTOCOL_CONF_OPT = --disable-shared
# TWAMP_PROTOCOL_MAKE_OPT = noinst_PROGRAMS=

ifeq ($(BR2_DSYSINIT),y)
TWAMP_PROTOCOL_DEPENDENCIES += deuteron_framework
TWAMP_PROTOCOL_LDFLAGS += -ld_service_notify -Wl,-rpath-link,$(STAGING_DIR)/lib -Wl,-rpath-link,$(STAGING_DIR)/usr/lib
endif

TWAMP_PROTOCOL_MAKE_OPT += CC="$(TARGET_CC)" LD="$(TARGET_LD)" CFLAGS="$(TARGET_CFLAGS) -g" LDFLAGS="$(TARGET_LDFLAGS) $(TWAMP_PROTOCOL_LDFLAGS)"

TWAMP_PROTOCOL_CLIENT = twamp_client
TWAMP_PROTOCOL_SERVER = twamp_server

# define TWAMP_PROTOCOL_INSTALL_STAGING_CMDS
# 	$(MAKE) -C $(@D) PREFIX="$(STAGING_DIR)/usr/sbin/" install
# endef

# BUILD
define TWAMP_PROTOCOL_BUILD_CMDS
	$(MAKE) -C $(@D) $(TWAMP_PROTOCOL_MAKE_OPT) all
endef

# INSTALL
# ifeq ($(BR2_TWAMP_PROTOCOL_CLIENT),y)
# 	mv $(@D)/client $(TARGET_DIR)$(TWAMP_PROTOCOL_DIR)/twamp-client
# else
# 	$(RM) -f $(@D)/client
# endif

# ifeq ($(BR2_TWAMP_PROTOCOL_SERVER),y)
# 	mv $(@D)/server $(TARGET_DIR)$(TWAMP_PROTOCOL_DIR)/twamp-server
# else
# 	$(RM) -f $(@D)/server
# endif

define TWAMP_PROTOCOL_INSTALL_TARGET_CMDS
	mv $(@D)/client $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_CLIENT)
	mv $(@D)/server $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_SERVER)
endef

# CLEAN
define TWAMP_PROTOCOL_CLEAN_CMDS
	$(TARGET_MAKE_ENV) DESTDIR="$(TARGET_DIR)" $(MAKE) -C $(@D) clean
	$(RM) -f $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_CLIENT)
	$(RM) -f $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_SERVER)
endef

# POST_HOOKS
ifneq ($(BR2_SUPPORT_TWAMP_CLIENT),y)
define TWAMP_PROTOCOL_CLIENT_REMOVE
	$(RM) $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_CLIENT)
endef
TWAMP_PROTOCOL_POST_INSTALL_TARGET_HOOKS += TWAMP_PROTOCOL_CLIENT_REMOVE
endif

ifneq ($(BR2_SUPPORT_TWAMP_SERVER),y)
define TWAMP_PROTOCOL_SERVER_REMOVE
	$(RM) $(TARGET_DIR)$(TWAMP_PROTOCOL_TARGET_DIR)/$(TWAMP_PROTOCOL_SERVER)
endef
TWAMP_PROTOCOL_POST_INSTALL_TARGET_HOOKS += TWAMP_PROTOCOL_SERVER_REMOVE
endif

$(eval $(call GENTARGETS))
