#############################################################
#
# mosquitto
#
#############################################################

LIBUMQTT_VERSION = dru

LIBUMQTT_SITE_METHOD = git
LIBUMQTT_SUPPORTS_IN_SOURCE_BUILD = NO
LIBUMQTT_SITE = $(DLINK_GIT_STORAGE)/libumqtt
LIBUMQTT_DEPENDENCIES = libev
#LIBUMQTT_LICENSE = EPL-1.0
#LIBUMQTT_LICENSE_FILES = epl-v10 edl-v10
LIBUMQTT_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_LUA),y)
LIBUMQTT_CONF_OPT += -DUMQTT_LUA_SUPPORT=ON
LIBUMQTT_DEPENDENCIES += lua
else
LIBUMQTT_CONF_OPT += -DUMQTT_LUA_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBUMQTT_CONF_OPT += -DUMQTT_SSL_SUPPORT=ON -DUMQTT_USE_OPENSSL=ON
LIBUMQTT_DEPENDENCIES += openssl
else
LIBUMQTT_CONF_OPT += -DUMQTT_SSL_SUPPORT=OFF
endif


$(eval $(call CMAKETARGETS))
