/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Jul 26 17:40:30 2017. */

#ifndef PB_APSON_CONFIG_APSON_CONFIG_PB_H_INCLUDED
#define PB_APSON_CONFIG_APSON_CONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _apson_config_msg {
    char checksum[36];
/* @@protoc_insertion_point(struct:apson_config_msg) */
} apson_config_msg;

typedef struct _apson_config_wlan {
    char device[32];
    char ssid[32];
    char key[64];
    char encryption[64];
    char checksum[36];
/* @@protoc_insertion_point(struct:apson_config_wlan) */
} apson_config_wlan;

/* Default values for struct fields */

/* Initializer values for message structs */
#define apson_config_msg_init_default            {""}
#define apson_config_wlan_init_default           {"", "", "", "", ""}
#define apson_config_msg_init_zero               {""}
#define apson_config_wlan_init_zero              {"", "", "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define apson_config_msg_checksum_tag            1
#define apson_config_wlan_device_tag             1
#define apson_config_wlan_ssid_tag               2
#define apson_config_wlan_key_tag                3
#define apson_config_wlan_encryption_tag         4
#define apson_config_wlan_checksum_tag           5

/* Struct field encoding specification for nanopb */
extern const pb_field_t apson_config_msg_fields[2];
extern const pb_field_t apson_config_wlan_fields[6];

/* Maximum encoded size of messages (where known) */
#define apson_config_msg_size                    38
#define apson_config_wlan_size                   238

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APSON_CONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
