/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon May 14 11:45:25 2018. */

#ifndef PB_APSON_REGISTER_APSON_REGISTER_PB_H_INCLUDED
#define PB_APSON_REGISTER_APSON_REGISTER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) apson_register_info_master_mac_t;
typedef PB_BYTES_ARRAY_T(6) apson_register_info_mac_t;
typedef PB_BYTES_ARRAY_T(16) apson_register_info_ap_ipv6_t;
typedef struct _apson_register_info {
    char domain[32];
    apson_register_info_master_mac_t master_mac;
    char name[32];
    char location[32];
    char serial_num[15];
    apson_register_info_mac_t mac;
    char model_name[16];
    uint32_t radio0_type;
    uint32_t radio0_mimo_streams;
    uint32_t radio1_type;
    uint32_t radio1_mimo_streams;
    uint32_t radio2_type;
    uint32_t radio2_mimo_streams;
    char main_image_ver[16];
    char backup_image_ver[16];
    uint32_t ap_ipv4;
    apson_register_info_ap_ipv6_t ap_ipv6;
    char ap_description[128];
    uint32_t ap_uptime;
    uint32_t register_timestamp;
    uint32_t ipv4_mask;
    uint32_t ipv4_gateway;
    uint32_t last_reboot_reason;
    uint32_t ap_sm_state;
    uint32_t last_update_timestamp;
    uint32_t campaigner_priority;
    char latest_image_ver[16];
    int32_t region_en;
    char region_id[16];
    char oui[8];
    int32_t dl_progress;
    int32_t dl_status;
/* @@protoc_insertion_point(struct:apson_register_info) */
} apson_register_info;

/* Default values for struct fields */

/* Initializer values for message structs */
#define apson_register_info_init_default         {"", {0, {0}}, "", "", "", {0, {0}}, "", 0, 0, 0, 0, 0, 0, "", "", 0, {0, {0}}, "", 0, 0, 0, 0, 0, 0, 0, 0, "", 0, "", "", 0, 0}
#define apson_register_info_init_zero            {"", {0, {0}}, "", "", "", {0, {0}}, "", 0, 0, 0, 0, 0, 0, "", "", 0, {0, {0}}, "", 0, 0, 0, 0, 0, 0, 0, 0, "", 0, "", "", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define apson_register_info_domain_tag           1
#define apson_register_info_master_mac_tag       2
#define apson_register_info_name_tag             3
#define apson_register_info_location_tag         4
#define apson_register_info_serial_num_tag       5
#define apson_register_info_mac_tag              6
#define apson_register_info_model_name_tag       7
#define apson_register_info_radio0_type_tag      8
#define apson_register_info_radio0_mimo_streams_tag 9
#define apson_register_info_radio1_type_tag      10
#define apson_register_info_radio1_mimo_streams_tag 11
#define apson_register_info_radio2_type_tag      12
#define apson_register_info_radio2_mimo_streams_tag 13
#define apson_register_info_main_image_ver_tag   14
#define apson_register_info_backup_image_ver_tag 15
#define apson_register_info_ap_ipv4_tag          16
#define apson_register_info_ap_ipv6_tag          17
#define apson_register_info_ap_description_tag   18
#define apson_register_info_ap_uptime_tag        19
#define apson_register_info_register_timestamp_tag 20
#define apson_register_info_ipv4_mask_tag        21
#define apson_register_info_ipv4_gateway_tag     22
#define apson_register_info_last_reboot_reason_tag 23
#define apson_register_info_ap_sm_state_tag      24
#define apson_register_info_last_update_timestamp_tag 25
#define apson_register_info_campaigner_priority_tag 26
#define apson_register_info_latest_image_ver_tag 27
#define apson_register_info_region_en_tag        28
#define apson_register_info_region_id_tag        29
#define apson_register_info_oui_tag              30
#define apson_register_info_dl_progress_tag      31
#define apson_register_info_dl_status_tag        32

/* Struct field encoding specification for nanopb */
extern const pb_field_t apson_register_info_fields[33];

/* Maximum encoded size of messages (where known) */
#define apson_register_info_size                 524

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APSON_REGISTER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
