/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Aug 28 15:23:28 2017. */

#ifndef PB_APSON_CLIENT_APSON_CLIENT_PB_H_INCLUDED
#define PB_APSON_CLIENT_APSON_CLIENT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) apson_client_activity_mac_t;
typedef PB_BYTES_ARRAY_T(6) apson_client_activity_ap_mac_t;
typedef struct _apson_client_activity {
    apson_client_activity_mac_t mac;
    uint32_t snr;
    int32_t rssi;
    char ifname[16];
    uint32_t wlanmode;
    uint32_t tx_ss;
    uint32_t rx_ss;
    uint32_t bw;
    uint32_t reason;
    uint64_t to_client_tx_bytes;
    uint64_t to_client_rx_bytes;
    uint64_t to_client_tx_pkts;
    uint64_t to_client_rx_pkts;
    uint32_t state;
    apson_client_activity_ap_mac_t ap_mac;
/* @@protoc_insertion_point(struct:apson_client_activity) */
} apson_client_activity;

/* Default values for struct fields */

/* Initializer values for message structs */
#define apson_client_activity_init_default       {{0, {0}}, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}}
#define apson_client_activity_init_zero          {{0, {0}}, 0, 0, "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define apson_client_activity_mac_tag            1
#define apson_client_activity_snr_tag            2
#define apson_client_activity_rssi_tag           3
#define apson_client_activity_ifname_tag         4
#define apson_client_activity_wlanmode_tag       5
#define apson_client_activity_tx_ss_tag          6
#define apson_client_activity_rx_ss_tag          7
#define apson_client_activity_bw_tag             8
#define apson_client_activity_reason_tag         9
#define apson_client_activity_to_client_tx_bytes_tag 10
#define apson_client_activity_to_client_rx_bytes_tag 11
#define apson_client_activity_to_client_tx_pkts_tag 12
#define apson_client_activity_to_client_rx_pkts_tag 13
#define apson_client_activity_state_tag          14
#define apson_client_activity_ap_mac_tag         15

/* Struct field encoding specification for nanopb */
extern const pb_field_t apson_client_activity_fields[16];

/* Maximum encoded size of messages (where known) */
#define apson_client_activity_size               131

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APSON_CLIENT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
