/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon May 20 17:10:45 2019. */

#ifndef PB_AP_STATS_APSON_STATS_PB_H_INCLUDED
#define PB_AP_STATS_APSON_STATS_PB_H_INCLUDED
#include <pb.h>

#include "apson_db.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) ap_stats_ap_stats_ap_mac_t;
typedef struct _ap_stats_ap_stats {
    ap_stats_ap_stats_ap_mac_t ap_mac;
    uint32_t level;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_ap_stats) */
} ap_stats_ap_stats;

typedef struct _ap_stats_bin_data {
    apson_db_member_ap_wlan_stats_list wlan_bin;
    apson_db_member_ap_station_stats_list sta_bin;
    apson_db_wlan_bin_stats mesh_dl_bin;
    apson_db_wlan_bin_stats mesh_ul_bin;
/* @@protoc_insertion_point(struct:ap_stats_bin_data) */
} ap_stats_bin_data;

typedef PB_BYTES_ARRAY_T(6) ap_stats_bin_stats_ap_mac_t;
typedef struct _ap_stats_bin_stats {
    ap_stats_bin_stats_ap_mac_t ap_mac;
    uint32_t level;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_bin_stats) */
} ap_stats_bin_stats;

typedef PB_BYTES_ARRAY_T(6) ap_stats_kickout_client_client_mac_t;
typedef PB_BYTES_ARRAY_T(6) ap_stats_kickout_client_ap_mac_t;
typedef struct _ap_stats_kickout_client {
    ap_stats_kickout_client_client_mac_t client_mac;
    ap_stats_kickout_client_ap_mac_t ap_mac;
    char interface_name[17];
    uint32_t reason_code;
    uint32_t lock_tim;
/* @@protoc_insertion_point(struct:ap_stats_kickout_client) */
} ap_stats_kickout_client;

typedef PB_BYTES_ARRAY_T(6) ap_stats_last_released_image_info_ap_mac_t;
typedef struct _ap_stats_last_released_image_info {
    ap_stats_last_released_image_info_ap_mac_t ap_mac;
    char ap_model_name[17];
    char last_released_version[13];
/* @@protoc_insertion_point(struct:ap_stats_last_released_image_info) */
} ap_stats_last_released_image_info;

typedef PB_BYTES_ARRAY_T(6) ap_stats_mesh_stats_ap_mac_t;
typedef struct _ap_stats_mesh_stats {
    ap_stats_mesh_stats_ap_mac_t ap_mac;
    uint32_t level;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_mesh_stats) */
} ap_stats_mesh_stats;

typedef PB_BYTES_ARRAY_T(6) ap_stats_reboot_ap_ap_mac_t;
typedef struct _ap_stats_reboot_ap {
    ap_stats_reboot_ap_ap_mac_t ap_mac;
    uint32_t reason_code;
    uint32_t reboot_sec_later;
/* @@protoc_insertion_point(struct:ap_stats_reboot_ap) */
} ap_stats_reboot_ap;

typedef PB_BYTES_ARRAY_T(6) ap_stats_specific_target_ap_image_info_ap_mac_t;
typedef struct _ap_stats_specific_target_ap_image_info {
    uint32_t check_type;
    ap_stats_specific_target_ap_image_info_ap_mac_t ap_mac;
    char ap_model_name[13];
/* @@protoc_insertion_point(struct:ap_stats_specific_target_ap_image_info) */
} ap_stats_specific_target_ap_image_info;

typedef PB_BYTES_ARRAY_T(6) ap_stats_sta_stats_ap_mac_t;
typedef PB_BYTES_ARRAY_T(6) ap_stats_sta_stats_sta_mac_t;
typedef struct _ap_stats_sta_stats {
    ap_stats_sta_stats_ap_mac_t ap_mac;
    uint64_t wlan_id;
    ap_stats_sta_stats_sta_mac_t sta_mac;
    uint32_t level;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_sta_stats) */
} ap_stats_sta_stats;

typedef PB_BYTES_ARRAY_T(6) ap_stats_wlan_stats_ap_mac_t;
typedef struct _ap_stats_wlan_stats {
    ap_stats_wlan_stats_ap_mac_t ap_mac;
    uint64_t wlan_id;
    uint32_t level;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_wlan_stats) */
} ap_stats_wlan_stats;

typedef struct _ap_stats_ap_image_upgrade {
    uint32_t num_ap;
    pb_size_t ap_image_info_count;
    ap_stats_last_released_image_info ap_image_info[16];
/* @@protoc_insertion_point(struct:ap_stats_ap_image_upgrade) */
} ap_stats_ap_image_upgrade;

typedef struct _ap_stats_system_width_stats {
    ap_stats_ap_stats ap;
    ap_stats_wlan_stats wlan;
    ap_stats_sta_stats sta;
    ap_stats_mesh_stats mesh;
    bool next;
/* @@protoc_insertion_point(struct:ap_stats_system_width_stats) */
} ap_stats_system_width_stats;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ap_stats_reboot_ap_init_default          {{0, {0}}, 0, 0}
#define ap_stats_kickout_client_init_default     {{0, {0}}, {0, {0}}, "", 0, 0}
#define ap_stats_specific_target_ap_image_info_init_default {0, {0, {0}}, ""}
#define ap_stats_last_released_image_info_init_default {{0, {0}}, "", ""}
#define ap_stats_ap_image_upgrade_init_default   {0, 0, {ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default, ap_stats_last_released_image_info_init_default}}
#define ap_stats_ap_stats_init_default           {{0, {0}}, 0, 0}
#define ap_stats_wlan_stats_init_default         {{0, {0}}, 0, 0, 0}
#define ap_stats_sta_stats_init_default          {{0, {0}}, 0, {0, {0}}, 0, 0}
#define ap_stats_mesh_stats_init_default         {{0, {0}}, 0, 0}
#define ap_stats_system_width_stats_init_default {ap_stats_ap_stats_init_default, ap_stats_wlan_stats_init_default, ap_stats_sta_stats_init_default, ap_stats_mesh_stats_init_default, 0}
#define ap_stats_bin_stats_init_default          {{0, {0}}, 0, 0}
#define ap_stats_bin_data_init_default           {apson_db_member_ap_wlan_stats_list_init_default, apson_db_member_ap_station_stats_list_init_default, apson_db_wlan_bin_stats_init_default, apson_db_wlan_bin_stats_init_default}
#define ap_stats_reboot_ap_init_zero             {{0, {0}}, 0, 0}
#define ap_stats_kickout_client_init_zero        {{0, {0}}, {0, {0}}, "", 0, 0}
#define ap_stats_specific_target_ap_image_info_init_zero {0, {0, {0}}, ""}
#define ap_stats_last_released_image_info_init_zero {{0, {0}}, "", ""}
#define ap_stats_ap_image_upgrade_init_zero      {0, 0, {ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero, ap_stats_last_released_image_info_init_zero}}
#define ap_stats_ap_stats_init_zero              {{0, {0}}, 0, 0}
#define ap_stats_wlan_stats_init_zero            {{0, {0}}, 0, 0, 0}
#define ap_stats_sta_stats_init_zero             {{0, {0}}, 0, {0, {0}}, 0, 0}
#define ap_stats_mesh_stats_init_zero            {{0, {0}}, 0, 0}
#define ap_stats_system_width_stats_init_zero    {ap_stats_ap_stats_init_zero, ap_stats_wlan_stats_init_zero, ap_stats_sta_stats_init_zero, ap_stats_mesh_stats_init_zero, 0}
#define ap_stats_bin_stats_init_zero             {{0, {0}}, 0, 0}
#define ap_stats_bin_data_init_zero              {apson_db_member_ap_wlan_stats_list_init_zero, apson_db_member_ap_station_stats_list_init_zero, apson_db_wlan_bin_stats_init_zero, apson_db_wlan_bin_stats_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ap_stats_ap_stats_ap_mac_tag             1
#define ap_stats_ap_stats_level_tag              2
#define ap_stats_ap_stats_next_tag               3
#define ap_stats_bin_data_wlan_bin_tag           1
#define ap_stats_bin_data_sta_bin_tag            2
#define ap_stats_bin_data_mesh_dl_bin_tag        3
#define ap_stats_bin_data_mesh_ul_bin_tag        4
#define ap_stats_bin_stats_ap_mac_tag            1
#define ap_stats_bin_stats_level_tag             2
#define ap_stats_bin_stats_next_tag              3
#define ap_stats_kickout_client_client_mac_tag   1
#define ap_stats_kickout_client_ap_mac_tag       2
#define ap_stats_kickout_client_interface_name_tag 3
#define ap_stats_kickout_client_reason_code_tag  4
#define ap_stats_kickout_client_lock_tim_tag     5
#define ap_stats_last_released_image_info_ap_mac_tag 1
#define ap_stats_last_released_image_info_ap_model_name_tag 2
#define ap_stats_last_released_image_info_last_released_version_tag 3
#define ap_stats_mesh_stats_ap_mac_tag           1
#define ap_stats_mesh_stats_level_tag            2
#define ap_stats_mesh_stats_next_tag             3
#define ap_stats_reboot_ap_ap_mac_tag            1
#define ap_stats_reboot_ap_reason_code_tag       2
#define ap_stats_reboot_ap_reboot_sec_later_tag  3
#define ap_stats_specific_target_ap_image_info_check_type_tag 1
#define ap_stats_specific_target_ap_image_info_ap_mac_tag 2
#define ap_stats_specific_target_ap_image_info_ap_model_name_tag 3
#define ap_stats_sta_stats_ap_mac_tag            1
#define ap_stats_sta_stats_wlan_id_tag           2
#define ap_stats_sta_stats_sta_mac_tag           3
#define ap_stats_sta_stats_level_tag             4
#define ap_stats_sta_stats_next_tag              5
#define ap_stats_wlan_stats_ap_mac_tag           1
#define ap_stats_wlan_stats_wlan_id_tag          2
#define ap_stats_wlan_stats_level_tag            3
#define ap_stats_wlan_stats_next_tag             4
#define ap_stats_ap_image_upgrade_num_ap_tag     1
#define ap_stats_ap_image_upgrade_ap_image_info_tag 2
#define ap_stats_system_width_stats_ap_tag       1
#define ap_stats_system_width_stats_wlan_tag     2
#define ap_stats_system_width_stats_sta_tag      3
#define ap_stats_system_width_stats_mesh_tag     4
#define ap_stats_system_width_stats_next_tag     5

/* Struct field encoding specification for nanopb */
extern const pb_field_t ap_stats_reboot_ap_fields[4];
extern const pb_field_t ap_stats_kickout_client_fields[6];
extern const pb_field_t ap_stats_specific_target_ap_image_info_fields[4];
extern const pb_field_t ap_stats_last_released_image_info_fields[4];
extern const pb_field_t ap_stats_ap_image_upgrade_fields[3];
extern const pb_field_t ap_stats_ap_stats_fields[4];
extern const pb_field_t ap_stats_wlan_stats_fields[5];
extern const pb_field_t ap_stats_sta_stats_fields[6];
extern const pb_field_t ap_stats_mesh_stats_fields[4];
extern const pb_field_t ap_stats_system_width_stats_fields[6];
extern const pb_field_t ap_stats_bin_stats_fields[4];
extern const pb_field_t ap_stats_bin_data_fields[5];

/* Maximum encoded size of messages (where known) */
#define ap_stats_reboot_ap_size                  20
#define ap_stats_kickout_client_size             47
#define ap_stats_specific_target_ap_image_info_size 29
#define ap_stats_last_released_image_info_size   42
#define ap_stats_ap_image_upgrade_size           710
#define ap_stats_ap_stats_size                   16
#define ap_stats_wlan_stats_size                 27
#define ap_stats_sta_stats_size                  35
#define ap_stats_mesh_stats_size                 16
#define ap_stats_system_width_stats_size         104
#define ap_stats_bin_stats_size                  16
#define ap_stats_bin_data_size                   44672

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APSON_STATS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
