/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Wed Jul 26 17:40:30 2017. */

#ifndef PB_EXAMPLE_APSONPBAPI_PB_H_INCLUDED
#define PB_EXAMPLE_APSONPBAPI_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Example_ExEnum {
    Example_ExEnum_First = 0,
    Example_ExEnum_Second = 1,
    Example_ExEnum_Third = 2
} Example_ExEnum;
#define _Example_ExEnum_MIN Example_ExEnum_First
#define _Example_ExEnum_MAX Example_ExEnum_Third
#define _Example_ExEnum_ARRAYSIZE ((Example_ExEnum)(Example_ExEnum_Third+1))

/* Struct definitions */
typedef struct _Example_SubMessage {
    int32_t subint32;
    char substring[32];
/* @@protoc_insertion_point(struct:Example_SubMessage) */
} Example_SubMessage;

typedef PB_BYTES_ARRAY_T(16) Example_alltypes_opt_bytes_t;
typedef struct _Example_alltypes {
    int32_t opt_int32;
    int64_t opt_int64;
    uint32_t opt_uint32;
    uint64_t opt_uint64;
    int32_t opt_sint32;
    int64_t opt_sint64;
    bool opt_bool;
    float opt_float;
    double opt_double;
    Example_ExEnum opt_enum;
    char opt_string[32];
    Example_alltypes_opt_bytes_t opt_bytes;
    Example_SubMessage opt_submsg;
    pb_size_t rep_int32_count;
    int32_t rep_int32[3];
    pb_size_t rep_submsg_count;
    Example_SubMessage rep_submsg[5];
/* @@protoc_insertion_point(struct:Example_alltypes) */
} Example_alltypes;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Example_SubMessage_init_default          {0, ""}
#define Example_alltypes_init_default            {0, 0, 0, 0, 0, 0, 0, 0, 0, (Example_ExEnum)0, "", {0, {0}}, Example_SubMessage_init_default, 0, {0, 0, 0}, 0, {Example_SubMessage_init_default, Example_SubMessage_init_default, Example_SubMessage_init_default, Example_SubMessage_init_default, Example_SubMessage_init_default}}
#define Example_SubMessage_init_zero             {0, ""}
#define Example_alltypes_init_zero               {0, 0, 0, 0, 0, 0, 0, 0, 0, (Example_ExEnum)0, "", {0, {0}}, Example_SubMessage_init_zero, 0, {0, 0, 0}, 0, {Example_SubMessage_init_zero, Example_SubMessage_init_zero, Example_SubMessage_init_zero, Example_SubMessage_init_zero, Example_SubMessage_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Example_SubMessage_subint32_tag          1
#define Example_SubMessage_substring_tag         2
#define Example_alltypes_opt_int32_tag           1
#define Example_alltypes_opt_int64_tag           2
#define Example_alltypes_opt_uint32_tag          3
#define Example_alltypes_opt_uint64_tag          4
#define Example_alltypes_opt_sint32_tag          5
#define Example_alltypes_opt_sint64_tag          6
#define Example_alltypes_opt_bool_tag            7
#define Example_alltypes_opt_float_tag           8
#define Example_alltypes_opt_double_tag          9
#define Example_alltypes_opt_enum_tag            10
#define Example_alltypes_opt_string_tag          11
#define Example_alltypes_opt_bytes_tag           12
#define Example_alltypes_opt_submsg_tag          13
#define Example_alltypes_rep_int32_tag           14
#define Example_alltypes_rep_submsg_tag          15

/* Struct field encoding specification for nanopb */
extern const pb_field_t Example_SubMessage_fields[3];
extern const pb_field_t Example_alltypes_fields[16];

/* Maximum encoded size of messages (where known) */
#define Example_SubMessage_size                  45
#define Example_alltypes_size                    441

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define APSONPBAPI_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
