/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Jan 19 11:13:47 2018. */

#ifndef PB_AUTO_ASGMT_AUTO_ASGMT_PB_H_INCLUDED
#define PB_AUTO_ASGMT_AUTO_ASGMT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) auto_asgmt_site_survey_info_ap_mac_t;
typedef struct _auto_asgmt_site_survey_info {
    auto_asgmt_site_survey_info_ap_mac_t ap_mac;
    uint32_t radio;
    uint32_t err_reason;
    uint32_t ch_cnt;
    pb_size_t ch_list_count;
    uint32_t ch_list[64];
/* @@protoc_insertion_point(struct:auto_asgmt_site_survey_info) */
} auto_asgmt_site_survey_info;

/* Default values for struct fields */

/* Initializer values for message structs */
#define auto_asgmt_site_survey_info_init_default {{0, {0}}, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define auto_asgmt_site_survey_info_init_zero    {{0, {0}}, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define auto_asgmt_site_survey_info_ap_mac_tag   1
#define auto_asgmt_site_survey_info_radio_tag    2
#define auto_asgmt_site_survey_info_err_reason_tag 3
#define auto_asgmt_site_survey_info_ch_cnt_tag   4
#define auto_asgmt_site_survey_info_ch_list_tag  5

/* Struct field encoding specification for nanopb */
extern const pb_field_t auto_asgmt_site_survey_info_fields[6];

/* Maximum encoded size of messages (where known) */
#define auto_asgmt_site_survey_info_size         410

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define AUTO_ASGMT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
