#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import json

for arg in sys.argv[1:]:
	f = open(arg, "r")
	# местный ублюдский json при дампе
	# зачем-то ставит пробелы перед переводом
	# строки. Делаем w/a

	try:
		s = json.dumps(json.loads(f.read()), sort_keys=True, indent=4).replace(", \n", ",\n")
	except ValueError as e:
		print("Wrong file {0}: {1}".format(arg, e))
		continue
	finally:
		f.close()

	f = open(arg, "w")
	f.write(s)
	f.write("\n")
	f.close()
sys.exit(0)
