# Kernel-specific options for Realtek 819X

ifeq ($(RLX_819X),y)

# Netlink monitor 2.0
define KERNEL_NEW_NETLINK_MONITOR_ENABLE
@$(call MESSAGE,"Enabling new netlink monitor") ;
@$(call KCONFIG_ENABLE_OPT,CONFIG_NETLINK_MONITOR_NEW, $(LINUX_CONFIG)) ;
endef

define KERNEL_NEW_NETLINK_MONITOR_DISABLE
@$(call MESSAGE,"Disabling new netlink monitor") ;
@$(call KCONFIG_DISABLE_OPT,CONFIG_NETLINK_MONITOR_NEW, $(LINUX_CONFIG)) ;
endef

ifeq ($(BR2_DEUTERON_APPS_DLINKWATCHER_TARGET_NLMON),y)
LINUX_ADDONS += KERNEL_NEW_NETLINK_MONITOR_ENABLE
else
LINUX_ADDONS += KERNEL_NEW_NETLINK_MONITOR_DISABLE
endif

# 802.1p
define KERNEL_VLAN_REMARKING_ENABLE
@$(call MESSAGE,"Enabling vlan remarking") ;
@$(call KCONFIG_ENABLE_OPT,CONFIG_DLINK_VLAN_REMARKING, $(LINUX_CONFIG)) ;
endef

define KERNEL_VLAN_REMARKING_DISABLE
@$(call MESSAGE,"Disabling vlan remarking") ;
@$(call KCONFIG_DISABLE_OPT,CONFIG_DLINK_VLAN_REMARKING, $(LINUX_CONFIG)) ;
endef

ifeq ($(BR2_SUPPORT_VLAN_PRIORITY),y)
LINUX_ADDONS += KERNEL_VLAN_REMARKING_ENABLE
else
LINUX_ADDONS += KERNEL_VLAN_REMARKING_DISABLE
endif

# host speedup
define KERNEL_HOST_SPEEDUP_ENABLE
@$(call MESSAGE,"Enable host speedup");
@$(call KCONFIG_ENABLE_OPT,CONFIG_RTK_HOST_SPEEDUP, $(LINUX_CONFIG));
endef

ifeq ($(BR2_DLINK_TR069CLIENT_KERNEL_SPEEDUP),y)
LINUX_ADDONS += KERNEL_HOST_SPEEDUP_ENABLE
endif

# wifi channel scheme
define KERNEL_RLX_WIFI_DLINK_CHANNEL_SCHEME
@$(call MESSAGE,"Enable DLINK_WIFI_CHANNEL_SCHEME")
@$(call KCONFIG_ENABLE_OPT,CONFIG_DLINK_WIFI_CHANNEL_SCHEME, $(LINUX_CONFIG));
endef

# (for compatibility with SDK 1.0, remove when update driver)
ifeq ($(BR2_RTL8192CD_VER_3414B),y)
LINUX_ADDONS += KERNEL_RLX_WIFI_DLINK_CHANNEL_SCHEME
endif

endif # RLX_819X
